// Synthetic, local-only history fixtures. Never accepts a remote origin or database.
import assert from 'node:assert/strict';import {readFileSync,writeFileSync} from 'node:fs';import {DatabaseSync} from 'node:sqlite';
const f=JSON.parse(readFileSync('work/local-reset-fixture.json','utf8'));assert(f.database.startsWith('.wrangler/'));const sql=new DatabaseSync(f.database);sql.exec('PRAGMA busy_timeout=5000');const origin='http://localhost:5173';
async function req(path:string,data?:unknown,cookie='',expect=200){const r=await fetch(origin+path,{method:data?'POST':'GET',headers:{...(data?{'Content-Type':'application/json',Origin:origin}:{}),...(cookie?{cookie}:{})},...(data?{body:JSON.stringify(data)}:{})});const d:any=await r.json();assert.equal(r.status,expect,JSON.stringify(d));return {data:d,cookie:r.headers.get('set-cookie')?.split(';')[0]||cookie};}
assert.deepEqual((await req('/api/lobby')).data,{user:null});await req('/api/history',undefined,'',401);
const suffix=Date.now().toString().slice(-9),password='Navigation-local-915!',a=await req('/api/auth',{action:'register',username:'nav'+suffix,name:'导航验收',password}),b=await req('/api/auth',{action:'register',username:'navout'+suffix,name:'记录外部测试',password});
const empty=(await req('/api/lobby',undefined,a.cookie)).data;assert.equal(empty.activeRoom,null);assert(!('records'in empty));assert(!('tables'in empty));assert(!JSON.stringify(empty).includes('password'));
let room=(await req('/api/game',{action:'create',title:'导航验收 · 斗地主'},a.cookie)).data;const code=room.code;
let shared=(await req('/api/lobby',undefined,a.cookie)).data;assert.equal(shared.activeKind,'landlord');assert.equal(shared.activeRoom,code);
const ids:string[]=[];for(let i=0;i<28;i++){const id=crypto.randomUUID();ids.push(id);const kind=i<15?'landlord':i<23?'mahjong':'holdem';let result:any={kind,seats:[{id:a.data.user.id,name:'导航验收',delta:i%2?'7':'-7'},{id:'bot:'+i,name:'陪练',bot:true,delta:i%2?'-7':'7'}],log:[],winner:0,landlord:0,bid:1,multiplier:1};if(i===0)delete result.kind;if(kind==='mahjong')Object.assign(result,{winType:'draw',rules:{name:'旧版基础'}});if(kind==='holdem')Object.assign(result,{id,type:'fold',roundNumber:i-22,rules:{ante:'10',small:'20',big:'30'},board:[],pots:[],button:0,ended:Date.now()});sql.prepare('INSERT INTO records (id,room_code,result,created) VALUES (?,?,?,?)').run(id,code,JSON.stringify(result),Date.now()+i);}
const page0=(await req('/api/history',undefined,a.cookie)).data,page1=(await req('/api/history?page=1',undefined,a.cookie)).data;assert.equal(page0.total,28);assert.equal(page0.items.length,12);assert.equal(page1.items.length,12);assert(!page0.items.some((x:any)=>page1.items.some((y:any)=>x.id===y.id)));assert(page0.items.every((x:any)=>!('result'in x)));
for(const [game,total] of [['landlord',15],['mahjong',8],['holdem',5]]){const r=(await req('/api/history?game='+game,undefined,a.cookie)).data;assert.equal(r.total,total);assert(r.items.every((x:any)=>x.game===game));}
assert.equal((await req('/api/history',undefined,b.cookie)).data.total,0);await req('/api/history?id='+ids[0],undefined,b.cookie,404);const d=(await req('/api/history?id='+ids[0],undefined,a.cookie)).data;assert.equal(d.room_code,code);assert.equal(d.result.seats[0].id,a.data.user.id);
for(const query of ['game=other','scope=hidden','page=-1','page=abc'])await req('/api/history?'+query,undefined,a.cookie,400);
room=(await req('/api/game',{action:'leave',code,revision:room.revision},a.cookie)).data;assert(room.left);assert.equal((await req('/api/lobby',undefined,a.cookie)).data.activeRoom,null);
room=(await req('/api/holdem',{action:'create',capacity:4,mode:'practice',title:'整桌记录验收'},a.cookie)).data;shared=(await req('/api/lobby',undefined,a.cookie)).data;assert.equal(shared.activeKind,'holdem');assert.equal((await req('/api/game',{action:'join',code:room.code},a.cookie)).data.redirect,'/holdem?room='+room.code);assert.equal((await req('/api/holdem?room='+room.code,undefined,a.cookie)).data.game.seats.length,4);
await req('/api/holdem',{action:'end_table',code:room.code,revision:room.revision},a.cookie);const tables=(await req('/api/history?scope=tables',undefined,a.cookie)).data;assert.equal(tables.total,1);assert.equal(tables.items[0].code,room.code);assert.equal(tables.items[0].players.length,4);assert(!JSON.stringify(tables).includes('hand'));assert(!JSON.stringify(tables).includes('"id":"'+a.data.user.id+'"'));assert.equal((await req('/api/history?scope=tables',undefined,b.cookie)).data.total,0);
writeFileSync('work/navigation-preview.json',JSON.stringify({username:'nav'+suffix,password,cookie:a.cookie,code,database:f.database}));sql.close();console.log({result:'PASS',checks:'shared lobby, no lobby history, 3-game filters, stable pagination, legacy records, owner-only detail/archive, exact table summaries, existing game endpoints and cross-game entry'});
