import {test} from 'node:test';import assert from 'node:assert/strict';
import {evaluate,pokerRank} from '../lib/holdem/evaluate.ts';
import {newHoldem,holdemRules,holdemSeat,startHoldem,moveHoldem,timeoutHoldem,holdemOptions,holdemView,settlePots,closeHoldem,rebuyHoldem,type HoldemGame} from '../lib/holdem/engine.ts';
import {holdemDecision} from '../lib/holdem/bot.ts';
const card=(rank:number,suit=0)=>(rank===2?12:rank-3)*4+suit;
function game(capacity=4){const g=newHoldem('p0','玩家0',holdemRules({capacity}));g.seats=Array.from({length:capacity},(_,i)=>holdemSeat('p'+i,'玩家'+i,g.rules.initial));g.seats.forEach(s=>s.ready=true);startHoldem(g);return g;}
function invariant(g:HoldemGame){const tiles=[...g.deck,...g.burns,...g.board,...g.seats.flatMap(s=>s.hand)];assert.equal(tiles.length,52);assert.equal(new Set(tiles).size,52);assert(g.seats.every(s=>BigInt(s.stack)>=0n));const total=g.seats.reduce((n,s)=>n+BigInt(s.stack)+(['playing','runout'].includes(g.phase)?BigInt(s.total):0n),0n);assert.equal(total,g.seats.reduce((n,s)=>n+BigInt(s.brought),0n));}
test('holdem full 52-card five-card category frequencies match the standard distribution',()=>{const counts=Array(9).fill(0);for(let a=0;a<48;a++)for(let b=a+1;b<49;b++)for(let c=b+1;c<50;c++)for(let d=c+1;d<51;d++)for(let e=d+1;e<52;e++)counts[evaluate([a,b,c,d,e]).category]++;assert.deepEqual(counts,[1302540,1098240,123552,54912,10200,5108,3744,624,40]);});
test('ace-low straight, kicker, best five and suit-neutral ties',()=>{
 const wheel=[14,2,3,4,5].map(r=>card(r,r%4));assert.equal(evaluate(wheel).name,'顺子');assert.equal(evaluate(wheel).ranks[0],5);
 const royal=[10,11,12,13,14].map(r=>card(r));assert.equal(evaluate([...royal,card(2,1),card(2,2)]).name,'皇家同花顺');assert.equal(evaluate(royal).score,evaluate(royal.map(c=>c+1)).score);
 const base=[card(14),card(14,1),card(8),card(6)];assert(evaluate([...base,card(13,1)]).score>evaluate([...base,card(12,1)]).score);assert.throws(()=>evaluate([0,0,1,2,3]));assert.equal(pokerRank(48),2);
});
test('four to ten seats, custom ante and blinds, action order and no hole-card leak',()=>{assert.throws(()=>holdemRules({capacity:3}));assert.throws(()=>holdemRules({capacity:11}));assert.throws(()=>holdemRules({small:30,big:20}));for(const capacity of [4,10]){const g=game(capacity);invariant(g);assert.equal(g.turn,3);assert.equal(g.seats[1].stack,'970');assert.equal(g.seats[2].stack,'960');assert.equal(g.seats[3].stack,'990');const v=holdemView(g,'p0');assert.equal(v.seats[0].hand.length,2);assert(v.seats.slice(1).every(s=>!s.hand.length));assert(!('deck' in v));assert(!('burns'in v));while(g.street==='preflop'){const s=g.seats[g.turn],o=holdemOptions(g,s.id);moveHoldem(g,s.id,{action:o.check?'check':'call'});}assert.equal(g.board.length,3);assert.equal(g.burns.length,1);assert.equal(g.turn,1);invariant(g);}});
test('all-ins produce multiple side pots, uncalled refund, folded donors and odd chips',()=>{const seats=[100,300,300,500].map(total=>({total:String(total),folded:false}));assert.deepEqual(settlePots(seats,[4,3,2,1],0).awards,['400','600','0','200']);seats[0].folded=true;assert.deepEqual(settlePots(seats,[4,3,2,1],0).awards,['0','1000','0','200']);assert.deepEqual(settlePots([1,1,1].map(total=>({total:String(total),folded:false})),[9,9,8],2).awards,['2','1','0']);const huge='900719925474099300000';const p=settlePots([0,1,2,3].map(()=>({total:huge,folded:false})),[9,9,8,7],0);assert.equal(p.awards[0],(BigInt(huge)*2n).toString());});
test('short all-ins do not reopen a prior actor until cumulative full raise',()=>{const g=game();g.currentBet='100';g.lastRaise='100';for(const s of g.seats){s.bet='100';s.total='110';s.stack='890';s.actedAt='100';}g.turn=1;g.seats[1].stack='50';g.seats[1].actedAt=null;moveHoldem(g,'p1',{action:'allin'});assert.equal(g.currentBet,'150');g.turn=0;assert.equal(holdemOptions(g,'p0').canRaise,false);assert.throws(()=>moveHoldem(g,'p0',{action:'raise',amount:'250'}));g.turn=2;g.seats[2].stack='100';g.seats[2].actedAt=null;moveHoldem(g,'p2',{action:'allin'});assert.equal(g.currentBet,'200');g.turn=0;assert.equal(holdemOptions(g,'p0').canRaise,true);assert.equal(holdemOptions(g,'p0').minRaise,'300');});
test('big blind keeps option, timeout check/fold, folds never expose hole cards',()=>{const g=game();moveHoldem(g,'p3',{action:'call'});moveHoldem(g,'p0',{action:'call'});moveHoldem(g,'p1',{action:'call'});assert.equal(g.turn,2);assert.equal(g.street,'preflop');timeoutHoldem(g,g.deadline);assert.equal(g.street,'flop');assert.equal(g.turn,1);timeoutHoldem(g,g.deadline);assert.equal(g.seats[1].folded,false);moveHoldem(g,'p2',{action:'raise',amount:'60'});timeoutHoldem(g,g.deadline);assert.equal(g.seats[3].folded,true);while(g.phase==='playing')moveHoldem(g,g.seats[g.turn].id,{action:'fold'});assert.equal(g.result?.type,'fold');assert(g.result?.seats.every(s=>!s.hand.length));assert.equal(g.board.length,3);invariant(g);});
test('all-in runout is staged, final settlement conserved, abort refunds current hand',()=>{const g=game();while(g.phase==='playing'){const s=g.seats[g.turn],o=holdemOptions(g,s.id);moveHoldem(g,s.id,{action:o.canAllIn?'allin':o.check?'check':'call'});}assert.equal(g.phase,'runout');assert.equal(g.board.length,0);timeoutHoldem(g,g.deadline);assert.equal(g.board.length,3);timeoutHoldem(g,g.deadline);assert.equal(g.board.length,4);timeoutHoldem(g,g.deadline);assert.equal(g.phase,'finished');assert.equal(g.board.length,5);assert.equal(g.burns.length,3);invariant(g);assert.equal(g.result?.seats.reduce((n,s)=>n+BigInt(s.delta),0n),0n);const closed=game();moveHoldem(closed,'p3',{action:'allin'});closeHoldem(closed,true);assert.equal(closed.result?.type,'aborted');assert(closed.seats.every(s=>s.stack==='1000'));assert(closed.result?.seats.every(s=>s.hand.length===0));invariant(closed);});
test('rebuy counted as brought-in, cannot top up mid-hand or duplicate',()=>{const g=game();assert.throws(()=>rebuyHoldem(g,'p0'));closeHoldem(g,true);g.phase='finished';g.seats[0].stack='0';rebuyHoldem(g,'p0');assert.equal(g.seats[0].brought,'2000');assert.equal(holdemView(g,'p0').seats[0].net,'-1000');assert.throws(()=>rebuyHoldem(g,'p0'));});
test('random legal games 4–10 seats terminate and conserve all 52 cards and every chip',()=>{for(let capacity=4;capacity<=10;capacity++)for(let round=0;round<35;round++){const g=game(capacity);let moves=0;while(['playing','runout'].includes(g.phase)){assert(++moves<500);invariant(g);if(g.phase==='runout'){timeoutHoldem(g,g.deadline);continue;}const s=g.seats[g.turn],o=holdemOptions(g,s.id),draw=Math.random();moveHoldem(g,s.id,{action:draw<.13?'fold':draw<.35&&o.canAllIn?'allin':draw<.6&&o.canRaise?'raise':o.check?'check':'call',amount:o.minRaise});}invariant(g);assert.equal(g.phase,'finished');}});
test('bot decisions require only visible cards and always submit legal actions',()=>{for(const capacity of [4,10]){const g=game(capacity);let moves=0;while(['playing','runout'].includes(g.phase)){assert(++moves<300);if(g.phase==='runout')timeoutHoldem(g,g.deadline);else{const id=g.seats[g.turn].id;moveHoldem(g,id,holdemDecision(holdemView(g,id),id));}invariant(g);}assert.equal(g.phase,'finished');}});

test('won stacks can exceed creation limits; legal large raises remain exact',()=>{
 const g=newHoldem('a','甲',holdemRules({capacity:4,ante:'1'}));for(let i=1;i<4;i++)g.seats.push(holdemSeat(String(i),'朋友',g.rules.initial));g.seats.forEach(s=>{s.stack='9999999999999999';s.brought=s.stack;s.ready=true});startHoldem(g);const s=g.seats[g.turn];moveHoldem(g,s.id,{action:'raise',amount:'9007199254740993'});assert.equal(g.currentBet,'9007199254740993');assert.equal(s.bet,'9007199254740993');
});
