import {test} from 'node:test';import assert from 'node:assert/strict';
import {newGame,deal,bid,doubleChoice,play,timeout,DEFAULT_LANDLORD_RULES,landlordRules} from '../lib/game/engine.ts';
import {HAM,HAM_V4,customMahjongRules} from '../lib/mahjong/rules.ts';import {winPlans,canWin,type WinContext} from '../lib/mahjong/solver.ts';
function ddz(){const g=newGame('a','甲');g.seats.push({id:'b',name:'乙',ready:false,hand:[],plays:0,last:''},{id:'c',name:'丙',ready:false,hand:[],plays:0,last:''});g.rules={...DEFAULT_LANDLORD_RULES,springDouble:false};deal(g);bid(g,g.turn,3);return g;}
test('landlord simultaneous doubles affect only each farmer-landlord payment',()=>{const g=ddz();assert.equal(g.phase,'doubling');const l=g.landlord,a=(l+1)%3,b=(l+2)%3;doubleChoice(g,a,true);assert.throws(()=>doubleChoice(g,a,false));doubleChoice(g,b,false);doubleChoice(g,l,true);assert.equal(g.phase,'playing');g.seats[l].hand=[0];play(g,l,[0]);assert.equal(g.deltas[l],18);assert.equal(g.deltas[a],-12);assert.equal(g.deltas[b],-6);assert.equal(g.deltas.reduce((a,b)=>a+b),0);});
test('double timeout defaults to no, disabled rooms and old rooms retain original flow',()=>{const g=ddz();timeout(g,g.deadline);assert.equal(g.phase,'playing');assert.deepEqual(g.doubles,[false,false,false]);const old=newGame('a','甲');old.seats=g.seats;deal(old);bid(old,old.turn,3);assert.equal(old.phase,'playing');assert.throws(()=>landlordRules({allowDouble:'yes'}));});
const cards=(types:number[])=>{const ns=Array(34).fill(0);return types.map(t=>t*4+ns[t]++)};
function ctx(types:number[]):WinContext{const hand=cards(types);return{round:'test',hand,incoming:hand.at(-1)!,melds:[],wildcard:32,winType:'self',heaven:false,earth:false,flower:false,selfDrawUnit:2,noWildBonus:false,closedBonus:false,fourWildWin:true};}
test('mahjong strict switches reject entire seven-pair family and pure hands even through gates',()=>{const seven=ctx([0,0,3,3,6,6,9,9,12,12,18,18,27,27]);assert(canWin(seven));assert(!canWin({...seven,disabledWins:['seven']}));const gates=ctx([0,0,0,1,2,3,4,5,6,7,8,8,8,4]);assert(winPlans(gates).some(p=>p.family==='gates'));assert(!canWin({...gates,disabledWins:['pure']}));assert(!winPlans({...gates,disabledWins:['gates']}).some(p=>p.family==='gates'));});
test('four-wild loose and formed interpretations cannot bypass a strict ban',()=>{const c=ctx([0,2,5,8,10,13,17,20,24,28,32,32,32,32]);assert(canWin(c));assert(!canWin({...c,disabledWins:['fourWild']}));assert(!canWin({...c,disabledWins:['selfDraw']}));const rules=customMahjongRules(HAM,{disabledWins:['pure'],allowChi:false});assert.deepEqual(rules.disabledWins,['pure']);assert.equal(rules.allowChi,false);assert.deepEqual(HAM.disabledWins,[]);assert.equal(HAM_V4.disabledWins,undefined);assert.throws(()=>customMahjongRules(HAM,{disabledWins:['notAHand']}));});
