import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';import {DatabaseSync} from 'node:sqlite';
import {type ModernGame} from '../lib/mahjong/modern.ts';
const fixture=JSON.parse(readFileSync('work/local-reset-fixture.json','utf8'));assert(fixture.database.startsWith('.wrangler/'));const sql=new DatabaseSync(fixture.database);sql.exec('PRAGMA busy_timeout=5000');const origin='http://localhost:5173';let cookie='',room:any;
async function req(path:string,data?:object,expect=200){const res=await fetch(origin+path,{method:data?'POST':'GET',headers:{cookie,...(data?{'Content-Type':'application/json',Origin:origin}:{})},...(data?{body:JSON.stringify(data)}:{})});const d:any=await res.json();assert.equal(res.status,expect,JSON.stringify(d));if(res.headers.get('set-cookie'))cookie=res.headers.get('set-cookie')!.split(';')[0];return d;}
const user=await req('/api/auth',{action:'register',username:'house'+Date.now().toString().slice(-9),name:'规则接口验收',password:'House-local-only-914!'});
await req('/api/game',{action:'create',rules:{allowDouble:'no'}},400);
room=await req('/api/game',{action:'create',mode:'practice',rules:{allowDouble:false,bombDouble:false,springDouble:false}});assert.equal(room.game.rules.allowDouble,false);room=await req('/api/game',{action:'ready',code:room.code,revision:room.revision});let g=JSON.parse(sql.prepare('SELECT state FROM rooms WHERE code=?').get(room.code)!.state as string);g.turn=0;g.deadline=Date.now()+60000;g.practice.nextAt=0;sql.prepare('UPDATE rooms SET state=? WHERE code=?').run(JSON.stringify(g),room.code);room=await req('/api/game?room='+room.code);room=await req('/api/game',{action:'bid',value:3,code:room.code,revision:room.revision});assert.equal(room.game.phase,'playing');await req('/api/game',{action:'double',value:true,code:room.code,revision:room.revision},400);await req('/api/game',{action:'end_practice',code:room.code,revision:room.revision});
await req('/api/mahjong',{action:'create',customRules:{disabledWins:['wrong']}},400);
room=await req('/api/mahjong',{action:'create',mode:'practice',customRules:{allowChi:false,allowRobAddedKong:false,disabledWins:['seven','pure']}});assert.deepEqual(room.game.rules.disabledWins,['seven','pure']);assert.equal(room.game.rules.allowChi,false);assert.equal(room.game.rules.allowRobAddedKong,false);room=await req('/api/mahjong',{action:'ready',code:room.code,revision:room.revision});
const m=JSON.parse(sql.prepare('SELECT state FROM rooms WHERE code=?').get(room.code)!.state as string) as ModernGame;m.opening=false;m.pending=null;m.turn=0;m.wildcard=32;m.deadline=Date.now()+60000;m.practice!.nextAt=0;const types=[0,0,3,3,6,6,9,9,12,12,18,18,27,27],counts=Array(34).fill(0);m.seats[0].hand=types.map(t=>t*4+counts[t]++);m.drawn=m.seats[0].hand.at(-1)!;const used=new Set(m.seats[0].hand),rest=Array.from({length:136},(_,i)=>i).filter(x=>!used.has(x));m.seats.slice(1).forEach(s=>s.hand=rest.splice(0,13));m.wall=rest;
sql.prepare('UPDATE rooms SET state=? WHERE code=?').run(JSON.stringify(m),room.code);room=await req('/api/mahjong?room='+room.code);assert.equal(room.game.options.canHu,false);await req('/api/mahjong',{action:'hu',code:room.code,revision:room.revision},400);await req('/api/mahjong',{action:'end_practice',code:room.code,revision:room.revision});sql.close();console.log({result:'PASS',checks:'custom room snapshots, DDZ disabled doubling skips phase, server rejects invalid choices, mahjong strict seven-pair prohibition reaches live options/hu endpoint'});
