"use client";
import {useCallback,useEffect,useRef,useState} from 'react';
import {ArrowLeft,ArrowRight,Check,ChevronRight,Club,Copy,Crown,DoorOpen,History,Info,LogOut,Plus,RefreshCw,Settings,ShieldCheck,Timer,Users,X} from 'lucide-react';
import AuthScreen from '@/components/auth-screen';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogTrigger,DialogDescription} from '@/components/ui/dialog';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {AlertDialog,AlertDialogContent,AlertDialogHeader,AlertDialogTitle,AlertDialogDescription,AlertDialogFooter,AlertDialogCancel,AlertDialogAction} from '@/components/ui/alert-dialog';
import {Toaster,toast} from 'sonner';
import {api} from '@/lib/client';
import {classify,beats,face,suit,rank,hints} from '@/lib/game/engine';

type Player={id:string;name:string;username:string;role:string;score:number};
function Brand(){return <div className="brand"><span className="brand-icon"><Club size={21}/></span><span>三人局<small>好 友 游 戏 室</small></span></div>}
function Rules(){return <Dialog><DialogTrigger asChild><Button variant="ghost" aria-label="玩法规则"><Info size={17}/><span className="hide-small">玩法规则</span></Button></DialogTrigger><DialogContent className="rules-modal"><DialogHeader><DialogTitle>本桌规则</DialogTitle><DialogDescription>三人经典叫分 · 一副 54 张牌 · 无癞子</DialogDescription></DialogHeader><div className="rules-list"><p><b>叫分</b>每人先拿 17 张。轮流叫 1、2、3 分或不叫；需高于当前分。叫 3 分或最高叫分后连续两人不叫时确定地主。无人叫分就重新发牌。</p><p><b>出牌</b>地主拿走并公开 3 张底牌，首先出牌。单张、对子、三张、三带一、三带二、顺子、连对、飞机、四带二、炸弹、王炸均可使用。顺子至少 5 张，连对至少 3 对；连续牌型不含 2 和王。</p><p><b>带牌约定</b>飞机至少两组三张；单翼可组成对子，不能带三张、四张或双王；对翼需为不同点数的对子。四带二可带一对，但不能带双王；四带两对的对子点数必须不同。</p><p><b>压牌</b>相同牌型、相同长度比主体点数；炸弹可以压普通牌，王炸最大。连续两人不出后，由上一位出牌者重新领出。</p><p><b>计分</b>任一农民出完即农民方获胜。单个农民输赢分数 = 叫分 × 倍数，地主为两倍。每个炸弹、王炸翻倍；春天或反春天再翻倍。仅娱乐积分。</p><p><b>超时与掉线</b>超时叫分默认为不叫；跟牌默认不出；领出默认最小单张。掉线后登录并返回原房间即可继续。所有人离线时暂停推进，重新进入后恢复。</p></div></DialogContent></Dialog>}
function Card({card,selected=false,onClick,small=false}:{card:number;selected?:boolean;onClick?:()=>void;small?:boolean}){const red=card===53||(card<52&&[1,3].includes(card%4));const inner=<><b>{face(card)}</b><span>{suit(card)}</span><i>{suit(card)}</i></>;return onClick?<button type="button" onClick={onClick} aria-pressed={selected} aria-label={`${suit(card)}${face(card)}`} className={`playing-card hand-card ${red?'red':''} ${selected?'selected':''} ${card>=52?'joker':''}`}>{inner}</button>:<div className={`playing-card ${red?'red':''} ${small?'mini-card':''} ${card>=52?'joker':''}`}>{inner}</div>}
function Avatar({name,index=0}:{name:string;index?:number}){return <span className={`avatar avatar-${index%3}`}>{name.slice(0,1).toUpperCase()}</span>}
export default function Home(){
 const [user,setUser]=useState<Player|null>(null),[loaded,setLoaded]=useState(false),[lobby,setLobby]=useState<any>(null),[room,setRoom]=useState<any>(null),[code,setCode]=useState(''),[title,setTitle]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[selected,setSelected]=useState<number[]>([]),[clock,setClock]=useState(Date.now()),[createOpen,setCreateOpen]=useState(false),[leaveOpen,setLeaveOpen]=useState(false),[copied,setCopied]=useState(false);
 const roomRef=useRef<any>(null),userRef=useRef<Player|null>(null);roomRef.current=room;userRef.current=user;
 const acceptRoom=useCallback((next:any)=>setRoom((prev:any)=>!prev||prev.code!==next.code||next.revision>=prev.revision?{...next,receivedAt:Date.now()}:prev),[]);
 const fail=useCallback((e:any)=>{setError(e.message||'连接失败，正在重试');if(e.status===401||e.status===403){setUser(null);setRoom(null)}},[]);
 const loadLobby=useCallback(async()=>{const d=await api('/api/game');setLobby(d);setUser(d.user);return d},[]);
 useEffect(()=>{const requested=new URLSearchParams(location.search).get('room');if(requested&&/^\d{6}$/.test(requested))setCode(requested);api('/api/auth').then(d=>setUser(d.user)).catch(e=>setError(e.message)).finally(()=>setLoaded(true));},[]);
 useEffect(()=>{if(!user?.id)return;loadLobby().catch(fail)},[user?.id,loadLobby,fail]);
 useEffect(()=>{if(!room?.code)return;let active=true,pending=false;const poll=async()=>{if(pending)return;pending=true;try{const d=await api('/api/game?room='+room.code);if(active){acceptRoom(d);setError('')}}catch(e){if(active)fail(e)}finally{pending=false}};const id=setInterval(poll,1500);return()=>{active=false;clearInterval(id)}},[room?.code,acceptRoom,fail]);
 useEffect(()=>{const id=setInterval(()=>setClock(Date.now()),250);return()=>clearInterval(id)},[]);
 useEffect(()=>{setSelected([])},[room?.game?.turn,room?.game?.round,room?.game?.seats?.find((s:any)=>s.id===user?.id)?.hand?.join(',')]);
 async function act(action:string,extra:any={}){if(busy)return;setBusy(true);setError('');try{const r=roomRef.current;const d=await api('/api/game',{action,code:r?.code||code,revision:r?.revision,...extra});if(d.left){setRoom(null);await loadLobby()}else acceptRoom(d);setCreateOpen(false);setLeaveOpen(false);return d}catch(e:any){setError(e.message);if(e.status===409&&roomRef.current){api('/api/game?room='+roomRef.current.code).then(acceptRoom).catch(fail)}throw e}finally{setBusy(false)}}
 const doAct=(action:string,extra:any={})=>{void act(action,extra).catch(()=>{})};
 const actionRef=useRef(act);actionRef.current=act;
 useEffect(()=>{const context=(document as any).modelContext;if(!context?.registerTool||!user?.id)return;const control=new AbortController();for(const tool of [{name:'read_my_game',description:'Read the current room and only the cards this signed-in player is allowed to see.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},execute:async()=>({room:roomRef.current,user:userRef.current})},{name:'join_friend_room',description:'Join an existing friend room using its six-digit code. This takes a player seat.',inputSchema:{type:'object',properties:{code:{type:'string',pattern:'^[0-9]{6}$'}},required:['code'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:true},execute:async(input:any)=>{if(typeof input?.code!=='string'||!/^\d{6}$/.test(input.code))throw Error('房间号必须为 6 位数字');const d=await actionRef.current('join',{code:input.code});return{code:d.code,phase:d.game.phase}}}]){try{Promise.resolve(context.registerTool(tool,{signal:control.signal})).catch(()=>{})}catch{}}return()=>control.abort()},[user?.id]);
 async function copy(){try{await navigator.clipboard.writeText(`${location.origin}/?room=${room.code}`);setCopied(true);setTimeout(()=>setCopied(false),2000)}catch{toast('房间号：'+room.code)}}
 async function resume(){setBusy(true);try{acceptRoom(await api('/api/game?room='+lobby.activeRoom))}catch(e){fail(e)}finally{setBusy(false)}}
 if(!user)return <><AuthScreen onAuth={setUser}/>{loaded&&error&&<div className="floating-error" role="alert">{error}<button onClick={()=>location.reload()}>重试</button></div>}</>;
 const g=room?.game,seat=g?.seats.findIndex((s:any)=>s.id===user.id)??-1,me=g?.seats[seat],myTurn=g&&g.turn===seat,offset=room?room.serverNow-room.receivedAt:0,left=g?Math.max(0,Math.ceil((g.deadline-clock-offset)/1000)):0,combo=classify(selected),legal=combo&&beats(combo,g?.last?.combo??null);
 return <div className="app-shell"><Toaster theme="dark" position="top-center"/><header className="app-header"><Brand/><div className="header-right"><Rules/>{user.role==='admin'&&<Button variant="ghost" asChild><a href="/admin" aria-label="管理后台"><Settings size={17}/><span className="hide-small">管理后台</span></a></Button>}<span className="header-user"><Avatar name={user.name}/><span>{user.name}</span></span><Button variant="ghost" size="icon" aria-label="退出登录" onClick={()=>api('/api/auth',{action:'logout'}).then(()=>{setUser(null);setRoom(null);setLobby(null)})}><LogOut size={17}/></Button></div></header>
 {error&&<div className="connection-error" role="alert">{error}<button aria-label="关闭提示" onClick={()=>setError('')}><X size={16}/></button></div>}
 {!room?<div className="lobby-layout"><div className="lobby-main"><div className="lobby-heading"><span className="section-tag">好 友 牌 桌</span><h1>今天，和谁一桌？</h1><p>开一桌新的，或者加入朋友的房间。</p></div>{lobby?.config?.announcement&&<div className="announcement"><Info size={17}/><span>{lobby.config.announcement}</span></div>}
 <div className="game-tile"><div className="game-tile-info"><div className="game-index">01 <span>CLASSIC</span></div><h2>斗地主</h2><p>三人成局，默契加倍。</p><div className="game-tags"><span><Users size={15}/> 3 人</span><span>经典叫分</span><span>无癞子</span></div>{lobby?.activeRoom?<Button className="start-table" disabled={busy} onClick={resume}>返回房间 {lobby.activeRoom}<ArrowRight size={18}/></Button>:<Dialog open={createOpen} onOpenChange={setCreateOpen}><DialogTrigger asChild><Button className="start-table" disabled={lobby?.config?.maintenance}><Plus size={19}/>开个房间</Button></DialogTrigger><DialogContent><DialogHeader><DialogTitle>开一桌，等朋友</DialogTitle><DialogDescription>房间创建后，把邀请链接发给另外两位朋友。</DialogDescription></DialogHeader><form onSubmit={e=>{e.preventDefault();doAct('create',{title})}} className="stack-form"><label htmlFor="title">房间名称</label><Input id="title" maxLength={24} value={title} onChange={e=>setTitle(e.target.value)} placeholder={`${user.name} 的牌桌`}/><p className="muted">经典叫分 · 每步 {lobby?.config?.seconds||30} 秒</p><Button type="submit" disabled={busy}>{busy?'正在开桌…':'创建房间'}</Button></form></DialogContent></Dialog>}</div><div className="tile-cards" aria-hidden="true"><Card card={44}/><Card card={49}/><Card card={53}/></div><div className="tile-footer"><span>♠ ♥ ♣ ♦</span><span>输赢是过程，开心是正事。</span></div></div>
 <div className="join-box"><div><h3>朋友已经开桌了？</h3><p>输入 6 位房间号，马上入座。</p></div><form onSubmit={e=>{e.preventDefault();doAct('join')}}><Input aria-label="6 位房间号" placeholder="6 位房间号" inputMode="numeric" pattern="[0-9]{6}" maxLength={6} value={code} onChange={e=>setCode(e.target.value.replace(/\D/g,''))} required/><Button type="submit" disabled={busy||code.length!==6}>加入房间<ChevronRight size={17}/></Button></form></div>
 </div><aside className="lobby-aside"><div className="profile-card"><Avatar name={user.name}/><h3>{user.name}</h3><span>好友牌友</span><div className="profile-score"><span>娱乐积分</span><strong>{user.score>=0?'+':''}{user.score}</strong></div></div><div className="recent"><h3><History size={17}/>最近对局</h3>{!lobby?<p className="muted">正在读取…</p>:lobby.records.length===0?<div className="empty-history"><Club size={28}/><p>第一局，等你开场</p><span>完成对局后，记录会留在这里。</span></div>:lobby.records.map((r:any,i:number)=>{const p=r.result.seats.find((s:any)=>s.id===user.id);return <div className="history-row" key={i}><div><b>{p.delta>0?'赢下一局':'下局再来'}</b><span>房间 {r.room_code} · {new Date(r.created).toLocaleDateString('zh-CN')}</span></div><strong className={p.delta>0?'positive':'negative'}>{p.delta>0?'+':''}{p.delta}</strong></div>})}</div><p className="aside-note"><ShieldCheck size={16}/>仅娱乐积分，不涉及现金。</p></aside></div>:
 <main className="room-shell"><div className="room-toolbar"><div><Button variant="ghost" size="icon" aria-label="返回大厅" onClick={()=>{setRoom(null);loadLobby().catch(fail)}}><ArrowLeft size={19}/></Button><div><h2>{room.title}</h2><span>房间 {room.code} · 经典叫分</span></div></div><Button variant="outline" onClick={copy}>{copied?<Check size={16}/>:<Copy size={16}/>}<span>{copied?'已复制':'邀请朋友'}</span></Button></div>
 <div className={`game-table phase-${g.phase}`}><div className="table-hud"><span><Users size={15}/>{g.seats.length} / 3</span><div className="bottom-cards">{['playing','finished'].includes(g.phase)?g.bottom.map((c:number)=><Card card={c} key={c} small/>):[0,1,2].map(i=><div key={i} className="card-back">♣</div>)}</div><span><Timer size={15}/>{g.seconds} 秒 <i>·</i> 倍数 ×{g.multiplier}</span></div>
 <div className="opponents">{[1,2].map((off)=>{const idx=(seat+off)%3,s=g.seats[idx];return <div className={`opponent ${g.turn===idx&&['playing','bidding'].includes(g.phase)?'active-seat':''}`} key={off}>{s?<><Avatar name={s.name} index={off}/><strong>{s.name}</strong><span className={idx===g.landlord?'landlord-label':'seat-role'}>{idx===g.landlord?<><Crown size={13}/>地主</>:g.landlord<0?'牌友':'农民'}</span>{['playing','bidding'].includes(g.phase)?<span className="card-count">剩余 <b>{s.count}</b> 张</span>:<span className="ready-label">{s.ready?'✓ 已准备':'等待准备'}</span>}{s.last&&<span className="seat-bubble">{s.last}</span>}</>:<><span className="empty-seat"><Plus size={24}/></span><strong>虚位以待</strong><span>喊位朋友来</span></>}</div>})}</div>
 <div className="table-stage">{g.phase==='waiting'?<><div className="table-stamp">♣</div><h2>{g.seats.length<3?'等人齐，就开局':'三人已就位'}</h2><p>{g.seats.length<3?'把房间号发给朋友，三人准备后自动发牌。':'三位玩家全部准备后，自动开始发牌。'}</p><div className="room-code">{room.code.split('').map((n:string,i:number)=><span key={i}>{n}</span>)}</div></>:g.phase==='closed'?<><DoorOpen size={32}/><h2>这桌已结束</h2><p>管理员已关闭房间。未完成的对局不计分。</p><Button onClick={()=>{setRoom(null);loadLobby().catch(fail)}}>返回大厅</Button></>:g.phase==='finished'?<div className="result-panel"><Crown size={35}/><div className="section-tag">本 局 结 算</div><h2>{g.winner===g.landlord?'地主获胜':'农民获胜'}</h2><p>{g.spring?'春天翻倍 · ':''}底分 {g.bid} × {g.multiplier} 倍</p><div className="result-scores">{g.seats.map((s:any,i:number)=><div key={s.id}><span>{s.name}</span><strong className={g.deltas[i]>0?'positive':'negative'}>{g.deltas[i]>0?'+':''}{g.deltas[i]}</strong></div>)}</div><p className="muted">准备后再来一局，或者离座休息。</p></div>:g.phase==='bidding'?<><span className="section-tag">叫 分 阶 段</span><h2>{myTurn?'轮到你叫分':`等待 ${g.seats[g.turn].name} 叫分`}</h2><p>{g.bid?`当前最高 ${g.bid} 分`:'想当地主吗？先看看手里的牌。'}</p><div className="turn-clock">{left}<small>秒</small></div></>:<><div className="turn-status"><span>{myTurn?'轮到你出牌':`${g.seats[g.turn].name} 出牌中`}</span><span className="turn-clock small">{left}<small>秒</small></span></div>{g.last?<><p className="last-by">{g.seats[g.last.seat].name} · {g.last.combo.kind}</p><div className="played-hand">{g.last.cards.map((c:number)=><Card key={c} card={c} small/>)}</div></>:<div className="free-lead"><Club size={36}/><p>新一轮，自由出牌</p></div>}</>}</div>
 <div className="self-area"><div className="self-label"><div><Avatar name={user.name}/><strong>{user.name}</strong><span>{g.landlord===seat?'♛ 地主':g.landlord>=0?'农民':'你'}</span></div><span>{['playing','bidding'].includes(g.phase)?`${me?.count||0} 张手牌`:me?.ready?'已准备':'未准备'}</span></div>
 <div className="action-bar">{['waiting','finished'].includes(g.phase)?<><Button variant="ghost" onClick={()=>setLeaveOpen(true)} disabled={busy}>离开房间</Button><Button className="ready-button" onClick={()=>doAct('ready')} disabled={busy}>{me?.ready?'取消准备':g.phase==='finished'?'准备下一局':'准备好了'}{!me?.ready&&<Check size={18}/>}</Button></>:g.phase==='bidding'?myTurn?<>{[0,1,2,3].map(n=><Button key={n} disabled={busy||(n!==0&&n<=g.bid)} variant={n===0?'secondary':'default'} onClick={()=>doAct('bid',{value:n})}>{n?`${n} 分`:'不叫'}</Button>)}</>:<p>看看手牌，等你叫分</p>:g.phase==='playing'?<><Button variant="secondary" disabled={busy||!myTurn||!g.last} onClick={()=>doAct('pass')}>不出</Button><Button variant="outline" disabled={!myTurn||busy} onClick={()=>{const options=hints(me.hand,g.last?.combo??null);if(!options.length){toast('没有能压过的牌，可以选择不出');setSelected([])}else{const old=options.findIndex(cs=>cs.join(',')===[...selected].sort((a,b)=>rank(b)-rank(a)||a-b).join(','));setSelected(options[(old+1)%options.length]);}}}>提示</Button><Button variant="ghost" disabled={!selected.length} onClick={()=>setSelected([])}>重选</Button><Button className="play-button" disabled={busy||!myTurn||!legal} onClick={()=>doAct('play',{cards:selected})}>出牌{selected.length>0&&<small>{selected.length}</small>}</Button></>:null}</div>
 {['playing','bidding'].includes(g.phase)&&<><div className="hand-strip">{me?.hand.map((c:number)=><Card card={c} key={c} selected={selected.includes(c)} onClick={()=>setSelected(prev=>prev.includes(c)?prev.filter(x=>x!==c):[...prev,c])}/>)}</div><div className="hand-caption">{selected.length?combo?`${combo.kind}${g.last&&!legal?' · 无法压过上一手':''}`:'所选手牌无法组成牌型':'点击手牌选中，再点击出牌'}{selected.length>0&&<span>已选 {selected.length} 张</span>}</div></>}
 </div></div><div className="room-footnote"><span><ShieldCheck size={14}/>自动保存对局 · 超时自动操作</span><Dialog><DialogTrigger asChild><Button variant="ghost" size="sm"><History size={14}/>本局记录</Button></DialogTrigger><DialogContent><DialogHeader><DialogTitle>本局记录</DialogTitle><DialogDescription>本局公开操作，不显示其他玩家的未出手牌。</DialogDescription></DialogHeader><div className="game-log">{g.log.length?g.log.map((l:any,i:number)=><p key={i}><span>{new Date(l.at).toLocaleTimeString('zh-CN',{hour:'2-digit',minute:'2-digit'})}</span>{l.text}</p>):<p className="muted">准备开始后，操作会显示在这里。</p>}</div></DialogContent></Dialog></div></main>}
 <AlertDialog open={leaveOpen} onOpenChange={setLeaveOpen}><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>要离开这一桌吗？</AlertDialogTitle><AlertDialogDescription>你可以凭房间号再次加入尚未开始的房间。</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel>继续坐着</AlertDialogCancel><AlertDialogAction onClick={()=>doAct('leave')}>离开房间</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog></div>
}
