"use client";
import {RoomCodeCopy,RoomCodeDigits} from '@/components/room-code-copy';
import {TableEffectsProvider,SpringEffect} from '@/components/table-effects';
import Link from '@/components/site-navigation';
import {useSearchParams} from 'next/navigation';
import {useClub,useClubState,useRoomNavigation,HistoryEntry} from '@/components/club-provider';
import {DEFAULT_LANDLORD_RULES,type LandlordRules} from '@/lib/game/engine';
import {DEFAULT_LANDLORD_V3_RULES} from '@/lib/game/landlord-v3';
import {Switch} from '@/components/ui/switch';
import {useCallback,useEffect,useRef,useState} from 'react';
import {ArrowLeft,ArrowRight,Check,ChevronRight,Club,Copy,Crown,DoorOpen,History,Info,LogOut,Plus,RefreshCw,Settings,ShieldCheck,Timer,Users,X} from 'lucide-react';
import {RoomChat} from '@/components/room-chat';
import {PlayerChat,useChatBubbles} from '@/components/player-chat';
import {PokerSeatHand} from '@/components/round-hands';
import {soloPractice} from '@/lib/practice/types';
import {EmptyBotSeat,RemoveBotSeat} from '@/components/bot-seat';
import {TableSound} from '@/components/table-sound';
import AuthScreen from '@/components/auth-screen';
import {Bot} from 'lucide-react';
import {RoomMode,PracticeBanner} from '@/components/room-mode';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogTrigger,DialogDescription} from '@/components/ui/dialog';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {AlertDialog,AlertDialogContent,AlertDialogHeader,AlertDialogTitle,AlertDialogDescription,AlertDialogFooter,AlertDialogCancel,AlertDialogAction} from '@/components/ui/alert-dialog';
import {Toaster,toast} from 'sonner';
import {api} from '@/lib/client';
import {classify,beats,rank,hints} from '@/lib/game/engine';

import {Card,HandStrip,SeatAction} from '@/components/poker-table';

type Player={id:string;name:string;username:string;role:string;score:number};
function Brand(){return <div className="brand"><span className="brand-icon"><Club size={21}/></span><span>娱乐中心<small>好 友 游 戏 室</small></span></div>}
function Rules({rules=DEFAULT_LANDLORD_RULES}:{rules?:LandlordRules|{id?:string}}){const v3=rules?.id==='landlord-v3';return <Dialog><DialogTrigger asChild><Button variant="ghost" aria-label="玩法规则"><Info size={17}/><span className="hide-small">玩法规则</span></Button></DialogTrigger><DialogContent className="rules-modal"><DialogHeader><DialogTitle>本桌规则</DialogTitle><DialogDescription>{v3?'三人扩展赛制 · 金币、胜利点与装备仅限本桌':'三人经典叫分 · 一副 54 张牌 · 无癞子'}</DialogDescription></DialogHeader><div className="rules-list">{v3?<><p><b>赛制</b>地主胜得 1 胜利点，农民胜各得 0.5 点；达到 4 点获整桌胜利。第 12 局无人达到时，最低分玩家各得 8 金币，进入三人突然死亡。</p><p><b>金币与商店</b>每人开局 2 金币。每个常规局先进入独立商店；测试装备无游戏效果，最多持有 8 件，可随时出售。第 13 局不刷新商店，也不发放金币。</p><p><b>竞价</b>叫地主托管金币；后续抢地主返还前一位托管并加 1 金币。最终地主胜则返还托管后收取农民付款，农民胜则瓜分托管。</p><p><b>突然死亡</b>第 13 局三人各 18 张、没有地主和底牌；任一玩家先出完即获得整桌胜利。</p></>:<><p><b>叫分</b>每人先拿 17 张。轮流叫 1、2、3 分或不叫；需高于当前分。叫 3 分或最高叫分后连续两人不叫时确定地主。无人叫分就重新发牌。</p><p><b>出牌</b>地主拿走并公开 3 张底牌，首先出牌。单张、对子、三张、三带一、三带二、顺子、连对、飞机、四带二、炸弹、王炸均可使用。顺子至少 5 张，连对至少 3 对；连续牌型不含 2 和王。</p><p><b>计分</b>任一农民出完即农民方获胜。每名农民单独结算：叫分 × 公共倍数 × 地主个人倍数 × 自己的个人倍数。地主收付两名农民金额之和。炸弹/王炸翻倍：{(rules as LandlordRules).bombDouble?'开启':'关闭'}；春天/反春天翻倍：{(rules as LandlordRules).springDouble?'开启':'关闭'}。仅娱乐积分。</p><p><b>加倍</b>{(rules as LandlordRules).allowDouble?'叫分结束后，每人有一次选择 ×2 的机会。地主加倍影响两笔收支；农民只影响自己与地主的一笔，双方均加倍则该笔 ×4。超时默认不加倍。':'本桌不启用个人加倍。'}</p></>}</div></DialogContent></Dialog>}
function Avatar({name,index=0}:{name:string;index?:number}){return <span className={`avatar avatar-${index%3}`}>{name.slice(0,1).toUpperCase()}</span>}
export default function Home(){
 const {user,setUser,loaded,lobby,loadLobby}=useClub(),search=useSearchParams();
 const {openRoom,followRoom}=useRoomNavigation();

 const [room,setRoom]=useClubState<any>('landlord:room',null);
 const [code,setCode]=useClubState('landlord:code',''),[title,setTitle]=useClubState('landlord:title',''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[selected,setSelected]=useClubState<number[]>('landlord:selected',[]),[clock,setClock]=useState(Date.now()),[mode,setMode]=useClubState('landlord:mode','friends'),[createOpen,setCreateOpen]=useState(false),[leaveOpen,setLeaveOpen]=useState(false),[copied,setCopied]=useState(false);
 const [houseRules,setHouseRules]=useClubState('landlord:houseRules',{...DEFAULT_LANDLORD_RULES});
 const [variant,setVariant]=useClubState<'v2'|'v3'>('landlord:variant','v2');
 const {bubbles,onSnapshot}=useChatBubbles(room?.code,user?.id);
 const [effectsConnected,setEffectsConnected]=useState(true);
 const roomRef=useRef<any>(null),userRef=useRef<Player|null>(null);roomRef.current=room;userRef.current=user;
 const acceptRoom=useCallback((next:any)=>setRoom((prev:any)=>!prev||prev.code!==next.code||next.revision>=prev.revision?{...next,receivedAt:Date.now()}:prev),[setRoom]);
 const fail=useCallback((e:any)=>{setError(e.message||'连接失败，正在重试');if(e.status===401){setUser(null);setRoom(null)}else if(e.status===403){setRoom(null);void loadLobby(true).catch(()=>{})}},[setUser,setRoom,loadLobby]);
 useEffect(()=>{const requested=search.get('room');if(requested&&/^\d{6}$/.test(requested))setCode(requested);},[search,setCode]);
 useEffect(()=>{void loadLobby().catch(e=>setError(e.message));},[loadLobby]);

 useEffect(()=>{if(!room?.code)return;let active=true,pending=false;const poll=async()=>{if(pending)return;pending=true;try{const d=await api('/api/game?room='+room.code);if(active){acceptRoom(d);setEffectsConnected(true);setError('')}}catch(e){if(active){setEffectsConnected(false);fail(e)}}finally{pending=false}};void poll();const id=setInterval(poll,1500);return()=>{active=false;clearInterval(id)}},[room?.code,acceptRoom,fail]);
 useEffect(()=>{const id=setInterval(()=>setClock(Date.now()),250);return()=>clearInterval(id)},[]);
 const handKey=[room?.code,room?.game?.round,room?.game?.seats?.find((s:any)=>s.id===user?.id)?.hand?.join(',')].join(':');
 const [selectionHand,setSelectionHand]=useClubState('landlord:selectionHand','');
 useEffect(()=>{if(handKey!==selectionHand){setSelected([]);setSelectionHand(handKey)}},[handKey,selectionHand,setSelected,setSelectionHand]);
 async function act(action:string,extra:any={}){if(busy)return;setBusy(true);setError('');try{const r=roomRef.current;const d=await api('/api/game',{action,code:r?.code||code,revision:r?.revision,...extra});if(d.redirect)return await followRoom(d.redirect);if(d.left){setRoom(null);await loadLobby(true)}else acceptRoom(d);if(['create','join','end_table','end_practice'].includes(action)||d.game?.phase==='finished')await loadLobby(true);setCreateOpen(false);setLeaveOpen(false);return d}catch(e:any){setError(e.message);if(e.status===409&&roomRef.current){api('/api/game?room='+roomRef.current.code).then(acceptRoom).catch(fail)}throw e}finally{setBusy(false)}}
 const doAct=(action:string,extra:any={})=>{void act(action,extra).catch(()=>{})};
 const actionRef=useRef(act);actionRef.current=act;
 useEffect(()=>{const context=(document as any).modelContext;if(!context?.registerTool||!user?.id)return;const control=new AbortController();for(const tool of [{name:'read_my_game',description:'Read the current room and only the cards this signed-in player is allowed to see.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},execute:async()=>({room:roomRef.current,user:userRef.current})},{name:'join_friend_room',description:'Join an existing friend room using its six-digit code. This takes a player seat.',inputSchema:{type:'object',properties:{code:{type:'string',pattern:'^[0-9]{6}$'}},required:['code'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:true},execute:async(input:any)=>{if(typeof input?.code!=='string'||!/^\d{6}$/.test(input.code))throw Error('房间号必须为 6 位数字');const d=await actionRef.current('join',{code:input.code});return{code:d.code,phase:d.game.phase}}}]){try{Promise.resolve(context.registerTool(tool,{signal:control.signal})).catch(()=>{})}catch{}}return()=>control.abort()},[user?.id]);
 async function copy(){try{await navigator.clipboard.writeText(`${location.origin}/?room=${room.code}`);setCopied(true);setTimeout(()=>setCopied(false),2000)}catch{toast('房间号：'+room.code)}}
 async function resume(){if(!lobby?.activeRoom||!lobby.activeKind)return;setBusy(true);try{await openRoom(lobby.activeKind,lobby.activeRoom)}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 if(!loaded)return <main className="mj-loading">正在打开游戏室…</main>;
 if(!user)return <><AuthScreen onAuth={setUser}/>{loaded&&error&&<div className="floating-error" role="alert">{error}<button onClick={()=>loadLobby(true).catch(()=>{})}>重试</button></div>}</>;
 const g=room?.game,v3=g?.kind==='landlord-v3',seat=g?.seats.findIndex((s:any)=>s.id===user.id)??-1,me=g?.seats[seat],myTurn=g&&g.turn===seat,offset=room?room.serverNow-room.receivedAt:0,left=g?Math.max(0,Math.ceil((g.deadline-clock-offset)/1000)):0,combo=classify(selected),legal=combo&&beats(combo,g?.last?.combo??null);
 const solo=soloPractice(g||{}),botControls=g?.phase==='waiting'&&g.host===user.id&&!solo?{busy,add:()=>doAct('add_bot'),remove:(botId:string)=>doAct('remove_bot',{botId})}:undefined;
 return <TableEffectsProvider room={room} userId={user.id} connected={effectsConnected}><div className="app-shell"><Toaster theme="light" position="top-center"/><div className="club-game-tools"><TableSound room={room} userId={user.id} seconds={left}/><Rules rules={g?g.rules??{...DEFAULT_LANDLORD_RULES,allowDouble:false}:DEFAULT_LANDLORD_RULES}/></div>
 {error&&<div className="connection-error" role="alert">{error}<button aria-label="关闭提示" onClick={()=>setError('')}><X size={16}/></button></div>}
 {!room?<div className="lobby-layout"><div className="lobby-main"><div className="lobby-heading"><span className="section-tag">好 友 牌 桌</span><h1>今天，和谁一桌？</h1><p>开一桌新的，或者加入朋友的房间。</p></div>{lobby?.config?.announcement&&<div className="announcement"><Info size={17}/><span>{lobby.config.announcement}</span></div>}
 <div className="game-tile"><div className="game-tile-info"><div className="game-index">01 <span>CLASSIC</span></div><h2>斗地主</h2><p>三人成局，默契加倍。</p><div className="game-tags"><span><Users size={15}/> 3 人</span><span>经典叫分</span><span>无癞子</span></div>{lobby?.activeRoom?<Button className="start-table" disabled={busy} onClick={resume}>{lobby.activeKind==='mahjong'?'返回麻将桌':lobby.activeKind==='holdem'?'返回德州扑克桌':'返回房间'} {lobby.activeRoom}<ArrowRight size={18}/></Button>:<Dialog open={createOpen} onOpenChange={setCreateOpen}><div className="create-actions"><DialogTrigger asChild><Button className="start-table" disabled={lobby?.config?.maintenance} onClick={()=>setMode('friends')}><Plus size={19}/>开个房间</Button></DialogTrigger><Button variant="outline" className="practice-start" disabled={lobby?.config?.maintenance} onClick={()=>{setMode('practice');setCreateOpen(true)}}><Bot size={18}/>人机测试</Button></div><DialogContent><DialogHeader><DialogTitle>{mode==='practice'?'开一桌人机测试':'开一桌，等朋友'}</DialogTitle><DialogDescription>{mode==='practice'?'两位进阶陪练已准备好，你入座后即可开始。':'房间创建后，把邀请链接发给另外两位朋友。'}</DialogDescription></DialogHeader><form onSubmit={e=>{e.preventDefault();doAct('create',{title,mode,rules:variant==='v3'?DEFAULT_LANDLORD_V3_RULES:houseRules})}} className="stack-form"><RoomMode mode={mode} onChange={setMode} bots={2}/><fieldset className="house-switches"><legend>赛制</legend><label><span>经典 landlord-v2</span><Switch checked={variant==='v2'} onCheckedChange={checked=>checked&&setVariant('v2')}/></label><label><span>扩展 landlord-v3</span><Switch checked={variant==='v3'} onCheckedChange={checked=>checked&&setVariant('v3')}/></label></fieldset><label htmlFor="title">房间名称</label><Input id="title" maxLength={24} value={title} onChange={e=>setTitle(e.target.value)} placeholder={`${user.name} 的牌桌`}/>{variant==='v2'?<fieldset className="house-switches"><legend>本桌计分规则</legend>{([['allowDouble','叫分后允许个人加倍'],['bombDouble','炸弹与王炸翻倍'],['springDouble','春天与反春天翻倍']] as const).map(([key,label])=><label key={key}><span>{label}</span><Switch checked={houseRules[key]} onCheckedChange={value=>setHouseRules(r=>({...r,[key]:value}))}/></label>)}</fieldset>:<p className="muted">v3：2 金币开局，商店、竞价托管与 4 胜利点赛制均仅限本桌。</p>}<p className="muted">每步 {lobby?.config?.seconds||30} 秒</p><Button type="submit" disabled={busy}>{busy?'正在开桌…':'创建房间'}</Button></form></DialogContent></Dialog>}</div><div className="tile-cards" aria-hidden="true"><Card card={44}/><Card card={49}/><Card card={53}/></div><div className="tile-footer"><span>♠ ♥ ♣ ♦</span><span>输赢是过程，开心是正事。</span></div></div>
 <Link href="/mahjong" className="mahjong-entry"><div><h2>麻将 · 四人成桌</h2><p>136 张牌，慢慢打，慢慢聊。</p></div><span><ArrowRight size={21}/></span></Link>
 <div className="join-box"><div><h3>朋友已经开桌了？</h3><p>输入 6 位房间号，马上入座。</p></div><form onSubmit={e=>{e.preventDefault();doAct('join')}}><Input aria-label="6 位房间号" placeholder="6 位房间号" inputMode="numeric" pattern="[0-9]{6}" maxLength={6} value={code} onChange={e=>setCode(e.target.value.replace(/\D/g,''))} required/><Button type="submit" disabled={busy||code.length!==6}>加入房间<ChevronRight size={17}/></Button></form></div>
 </div><aside className="lobby-aside"><div className="profile-card"><Avatar name={user.name}/><h3>{user.name}</h3><span>好友牌友</span><div className="profile-score"><span>娱乐积分</span><strong>{user.score>=0?'+':''}{user.score}</strong></div></div><HistoryEntry game="landlord"/><p className="aside-note"><ShieldCheck size={16}/>仅娱乐积分，不涉及现金。</p></aside></div>:
 <main className="room-shell"><div className="room-toolbar"><div><Button variant="ghost" size="icon" aria-label="返回大厅" onClick={()=>{setRoom(null);loadLobby(true).catch(fail)}}><ArrowLeft size={19}/></Button><div><h2>{room.title}</h2><span>房间 {room.code}<RoomCodeCopy code={room.code} compact/> · {solo?'人机测试':g.practice?'好友 + 人机':v3?'扩展赛制 v3':'经典叫分'}</span></div></div>{solo?<Button variant="outline" disabled={g.phase==='closed'} onClick={()=>setLeaveOpen(true)}><DoorOpen size={16}/>结束测试</Button>:<Button variant="outline" onClick={copy}>{copied?<Check size={16}/>:<Copy size={16}/>}<span>{copied?'已复制':'邀请朋友'}</span></Button>}</div>{g.practice&&<PracticeBanner mixed={!solo}/>}
 <div className={`game-table landlord-board phase-${g.phase}`}><div className="table-hud"><span><Users size={15}/>{g.seats.length} / 3</span><div className="bottom-cards">{['playing','finished'].includes(g.phase)?g.bottom.map((c:number)=><Card card={c} key={c} small/>):[0,1,2].map(i=><div key={i} className="card-back">♣</div>)}</div><span><Timer size={15}/>{g.seconds} 秒 <i>·</i> {v3?`第 ${g.roundNumber||0} 局`:<>倍数 ×{g.multiplier}</>}</span></div>
 <div className="landlord-opponents">{[2,1].map((off)=>{const idx=(seat+off)%3,s=g.seats[idx];return <section className={`landlord-seat side-${off===2?'left':'right'}`} key={off} aria-label={`${s?.name||'空位'}的座位`}><div className={`opponent ${(g.phase==='doubling'?g.doubles?.[idx]===null:g.turn===idx&&['playing','bidding'].includes(g.phase))?'active-seat':''}`}>
  {s?<><PlayerChat bubble={bubbles[s.id]} align={off===2?'start':'end'}><Avatar name={s.name} index={off}/></PlayerChat><strong>{s.name}{s.bot&&<span className="bot-label">机器人</span>}</strong><span className={idx===g.landlord?'landlord-label':'seat-role'}>{idx===g.landlord?<><Crown size={13}/>地主</>:g.landlord<0?'牌友':'农民'}</span><span className="seat-score">{v3?`${g.coins?.[idx]??'0'} 金币 · ${g.victoryPoints?.[idx]??'0'} 点`:`本桌 ${s.tableScore>=0?'+':''}${s.tableScore??0}${!s.bot&&` · 积分 ${s.accountScore??0}`}`}</span><span className="card-count">{['playing','bidding','doubling'].includes(g.phase)?`剩余 ${s.count} 张`:s.ready?'已准备':'未准备'}</span>{s.bot&&<RemoveBotSeat id={s.id} name={s.name} controls={botControls}/>}</>:<EmptyBotSeat controls={botControls}/>}
 </div>{s&&g.phase==='finished'&&<PokerSeatHand hand={s.hand} name={s.name}/>} {s&&(g.phase!=='finished'||!s.hand.length)&&<SeatAction action={g.tableActions?.[idx]} active={(g.phase==='doubling'?g.doubles?.[idx]===null:g.turn===idx&&['playing','bidding'].includes(g.phase))} seconds={left} bidding={g.phase==='bidding'} doubling={g.phase==='doubling'} name={s.name}/>}</section>})}</div>
  <div className="table-stage">{g.phase==='waiting'?<><div className="table-stamp">♣</div><h2>{solo?'陪练已就位':g.seats.length<3?'等人齐，就开局':'三人已就位'}</h2><p>{solo?'点击准备，两位机器人陪你开始。':g.seats.length<3?'邀请朋友，或由房主在空位添加人机。':g.practice?'机器人已准备好，等每位朋友点击准备。':'三位玩家全部准备后，自动开始发牌。'}</p><RoomCodeDigits code={room.code}/></>:g.phase==='closed'?<><DoorOpen size={32}/><h2>这桌已结束</h2><p>房间已关闭，未完成的对局不计分。</p><Button onClick={()=>{setRoom(null);loadLobby(true).catch(fail)}}>返回大厅</Button></>:g.phase==='finished'?<div className="result-panel">{!v3&&<SpringEffect winner={g.winner} landlord={g.landlord} spring={g.spring}/>}<Crown size={35}/><div className="section-tag">本 局 结 算</div><h2>{v3&&g.champion>=0?`${g.seats[g.champion].name} 获得整桌胜利`:g.winner===g.landlord?'地主获胜':'农民获胜'}</h2><p>{v3?`胜利点 ${g.victoryPoints.join(' / ')} · 金币 ${g.coins.join(' / ')}`:`${g.spring?'春天翻倍 · ':''}底分 ${g.bid} × ${g.multiplier} 倍${g.doubles?.some(Boolean)?' · 另计个人加倍':''}`}</p><div className="result-scores">{g.seats.map((s:any,i:number)=><div key={s.id}><span>{s.name}</span><strong className={v3?'':'negative'}>{v3?`${g.victoryPoints[i]} 点 / ${g.coins[i]} 金币`:`${g.deltas[i]>0?'+':''}${g.deltas[i]}`}</strong></div>)}</div><p className="muted">{v3?(g.champion>=0?'整桌赛制已结束。':'点击准备继续下一局。'):g.practice?'人机测试不影响账号积分，点击准备即可再来一局。':'准备后再来一局，或者离座休息。'}</p></div>:g.phase==='shopping'?<span className="landlord-phase-note">商店阶段 · 每名玩家独立购买测试装备</span>:g.phase==='doubling'?<span className="landlord-phase-note">叫分已定 · 每位玩家选择是否加倍</span>:g.phase==='bidding'?<span className="landlord-phase-note">{v3?`竞价中 · 当前托管 ${g.stake} 金币`:`叫分中 · ${g.bid?`最高 ${g.bid} 分`:'等待叫地主'}`}</span>:<span className="landlord-phase-note">{!g.last?'自由出牌':''}</span>}</div>
 <div className="landlord-self-action">{g.phase==='finished'&&<PokerSeatHand hand={me.hand} name={user.name}/>} {(g.phase!=='finished'||!me.hand.length)&&<SeatAction action={g.tableActions?.[seat]} active={(g.phase==='doubling'?g.doubles?.[seat]===null:myTurn&&['playing','bidding'].includes(g.phase))} seconds={left} bidding={g.phase==='bidding'} doubling={g.phase==='doubling'} name={user.name}/>}</div>
  <div className="self-area"><div className="self-label"><div><PlayerChat bubble={bubbles[user.id]} align="start"><Avatar name={user.name}/></PlayerChat><strong>{user.name}</strong><span className="seat-score">{v3?`${g.coins?.[seat]??'0'} 金币 · ${g.victoryPoints?.[seat]??'0'} 胜利点`:`本桌 ${me?.tableScore>=0?'+':''}${me?.tableScore??0} · 积分 ${me?.accountScore??user.score}`}</span><span>{g.landlord===seat?'♛ 地主':g.landlord>=0?'农民':'你'}</span></div><span>{['playing','bidding','doubling'].includes(g.phase)?`${me?.count||0} 张手牌`:me?.ready?'已准备':'未准备'}</span></div>
  <div className="action-bar">{v3?(['waiting','finished'].includes(g.phase)?<><Button variant="ghost" onClick={()=>setLeaveOpen(true)} disabled={busy}>{solo?'结束测试':'离开房间'}</Button>{g.champion<0&&<Button className="ready-button" onClick={()=>doAct('ready')} disabled={busy}>{me?.ready?'取消准备':g.phase==='finished'?'准备下一局':'准备好了'}<Check size={18}/></Button>}</>:g.phase==='shopping'?<Button disabled={busy||me?.last==='商店完成'} onClick={()=>doAct('shop_done')}>{me?.last==='商店完成'?'等待其他玩家':'完成购买'}</Button>:g.phase==='bidding'?myTurn?<><Button variant="secondary" disabled={busy} onClick={()=>doAct('v3_bid',{call:false})}>不叫</Button><Button disabled={busy||BigInt(g.coins?.[seat]??'0')<=BigInt(g.stake??'0')} onClick={()=>doAct('v3_bid',{call:true})}>{g.landlord<0?'叫地主':'抢地主'} · {BigInt(g.stake??'0')+1n} 金币</Button></>:<p>等待竞价</p>:g.phase==='playing'?<><Button variant="secondary" disabled={busy||!myTurn||!g.last} onClick={()=>doAct('pass')}>不出</Button><Button variant="outline" disabled={!myTurn||busy} onClick={()=>{const options=hints(me.hand,g.last?.combo??null);setSelected(options[0]||[]);}}>提示</Button><Button variant="ghost" disabled={!selected.length} onClick={()=>setSelected([])}>重选</Button><Button className="play-button" disabled={busy||!myTurn||!legal} onClick={()=>doAct('play',{cards:selected})}>出牌{selected.length>0&&<small>{selected.length}</small>}</Button></>:null):(['waiting','finished'].includes(g.phase)?<><Button variant="ghost" onClick={()=>setLeaveOpen(true)} disabled={busy}>{solo?'结束测试':'离开房间'}</Button><Button className="ready-button" onClick={()=>doAct('ready')} disabled={busy}>{me?.ready?'取消准备':g.phase==='finished'?'准备下一局':'准备好了'}{!me?.ready&&<Check size={18}/>}</Button></>:g.phase==='doubling'?g.doubles?.[seat]===null?<><Button variant="outline" disabled={busy} onClick={()=>doAct('double',{value:false})}>不加倍</Button><Button disabled={busy} onClick={()=>doAct('double',{value:true})}>加倍 ×2</Button></>:<p>已选择，等待其他玩家</p>:g.phase==='bidding'?myTurn?<>{[0,1,2,3].map(n=><Button key={n} disabled={busy||(n!==0&&n<=g.bid)} variant={n===0?'secondary':'default'} onClick={()=>doAct('bid',{value:n})}>{n?`${n} 分`:'不叫'}</Button>)}</>:<p>看看手牌，等你叫分</p>:g.phase==='playing'?<><Button variant="secondary" disabled={busy||!myTurn||!g.last} onClick={()=>doAct('pass')}>不出</Button><Button variant="outline" disabled={!myTurn||busy} onClick={()=>{const options=hints(me.hand,g.last?.combo??null);if(!options.length){toast('没有能压过的牌，可以选择不出');setSelected([])}else{const old=options.findIndex(cs=>cs.join(',')===[...selected].sort((a,b)=>rank(b)-rank(a)||a-b).join(','));setSelected(options[(old+1)%options.length]);}}}>提示</Button><Button variant="ghost" disabled={!selected.length} onClick={()=>setSelected([])}>重选</Button><Button className="play-button" disabled={busy||!myTurn||!legal} onClick={()=>doAct('play',{cards:selected})}>出牌{selected.length>0&&<small>{selected.length}</small>}</Button></>:null)}</div>
  {v3&&g.phase==='shopping'&&<div className="v3-shop" aria-label="扩展赛制商店"><h3>测试装备商店</h3><p>{g.coins?.[seat]??'0'} 金币 · 已持有 {g.equipment?.[seat]?.length??0} / 8</p><div>{(g.shops?.[seat]?.offers||[]).map((offer:any)=><Button key={offer.offerId} variant="outline" disabled={busy||offer.bought||BigInt(g.coins?.[seat]??'0')<BigInt(offer.price)} onClick={()=>doAct('shop_buy',{offerId:offer.offerId})}>{offer.level} 级测试装备 · {offer.price} 金币{offer.bought?' · 已购买':''}</Button>)}</div><div>{(g.equipment?.[seat]||[]).map((item:any)=><Button key={item.instanceId} variant="ghost" disabled={busy} onClick={()=>doAct('shop_sell',{instanceId:item.instanceId})}>出售 {item.level} 级测试装备 · 返还 {item.level===1?'0':String(BigInt(item.price)/2n)} 金币</Button>)}</div></div>}
 {['playing','bidding','doubling'].includes(g.phase)&&<><HandStrip hand={me?.hand||[]} selected={selected} onChange={setSelected} round={room.code+g.round}/><div className="hand-caption">{selected.length?combo?`${combo.kind}${g.last&&!legal?' · 无法压过上一手':''}`:'所选手牌无法组成牌型':'点击或按住鼠标划选手牌，再点击出牌'}{selected.length>0&&<span>已选 {selected.length} 张</span>}</div></>}
 </div></div><div className="room-footnote"><span><ShieldCheck size={14}/>自动保存对局 · 超时自动操作</span><Dialog><DialogTrigger asChild><Button variant="ghost" size="sm"><History size={14}/>本局记录</Button></DialogTrigger><DialogContent><DialogHeader><DialogTitle>本局记录</DialogTitle><DialogDescription>本局公开操作，不显示其他玩家的未出手牌。</DialogDescription></DialogHeader><div className="game-log">{g.log.length?g.log.map((l:any,i:number)=><p key={i}><span>{new Date(l.at).toLocaleTimeString('zh-CN',{hour:'2-digit',minute:'2-digit'})}</span>{l.text}</p>):<p className="muted">准备开始后，操作会显示在这里。</p>}</div></DialogContent></Dialog></div></main>}
 {room&&<RoomChat key={room.code} userId={user.id} code={room.code} onSnapshot={onSnapshot} closed={g.phase==='closed'}/>}
 <AlertDialog open={leaveOpen} onOpenChange={setLeaveOpen}><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>{solo?'结束人机测试？':'要离开这一桌吗？'}</AlertDialogTitle><AlertDialogDescription>{solo?'本房间将关闭，已完成的测试记录保留。账号积分不受影响。':'你可以凭房间号再次加入尚未开始的房间。'}</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel>继续坐着</AlertDialogCancel><AlertDialogAction onClick={()=>doAct(solo?'end_practice':'leave')}>{solo?'结束测试':'离开房间'}</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog></div></TableEffectsProvider>
}
