"use client";
import { useState } from "react";
import { ArrowRight, Club, Diamond, Heart, LockKeyhole, Spade, Users } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Tabs, TabsList, TabsTrigger } from "@/components/ui/tabs";

export default function AuthScreen({onAuth,setup=false,token=""}:{onAuth:(user:any)=>void;setup?:boolean;token?:string}) {
  const [mode,setMode]=useState(setup?"setup":"login");
  const [busy,setBusy]=useState(false);const [error,setError]=useState("");
  async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setError("");setBusy(true);const f=new FormData(e.currentTarget);try{const r=await fetch("/api/auth",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:mode,username:f.get("username"),password:f.get("password"),name:f.get("name"),token})});const d:any=await r.json();if(!r.ok)throw Error(d.error);onAuth(d.user)}catch(e){setError((e as Error).message||"连接失败，请重试")}finally{setBusy(false)}}
  return <main className="entry"><header className="brand"><span className="brand-icon"><Club size={22}/></span><span>娱乐中心<small>好 友 游 戏 室</small></span></header><section className="entry-table"><div className="table-top"><span>好友游戏室 · CLUB</span><span><Users size={15}/> 斗地主 / 麻将</span></div><div className="table-center"><div className="suit-line"><Spade/><Heart/><Club/><Diamond/></div><p className="eyebrow">好朋友，老规矩。</p><h1>人齐了，<br/>就开一局。</h1><p className="intro">建个房间，喊上朋友。<br/>斗地主、麻将，现在随时能聚。</p><div className="display-hand" aria-label="扑克牌示意"><div className="playing-card black rotate-left"><b>A</b><span>♠</span><i>♠</i></div><div className="playing-card red"><b>A</b><span>♥</span><i>♥</i></div><div className="playing-card black rotate-right"><b>A</b><span>♣</span><i>♣</i></div></div></div><div className="table-bottom"><span>一张牌桌 · 几位朋友 · 一点默契</span><span>♠ ♥ ♣ ♦</span></div></section><section className="login-panel"><div className="login-inner"><div className="section-tag">入座之前</div><h2>{setup?"设置管理员账号":"欢迎来玩"}</h2><p className="muted">{setup?"为 MartinHamburger 设置密码，开启你的游戏室。":"登录你的账号，和朋友坐到一桌。"}</p>{!setup&&<Tabs value={mode} onValueChange={setMode}><TabsList className="auth-tabs"><TabsTrigger value="login">登录</TabsTrigger><TabsTrigger value="register">注册账号</TabsTrigger></TabsList></Tabs>}<form onSubmit={submit}><label htmlFor="username">用户名</label><Input name="username" minLength={3} maxLength={24} defaultValue={setup?"MartinHamburger":""} readOnly={setup} id="username" placeholder="输入你的用户名" autoComplete="username" required/><label htmlFor="password">密码</label><Input name="password" minLength={10} maxLength={128} id="password" type="password" placeholder="至少 10 位字符" autoComplete={mode==="login"?"current-password":"new-password"} required/>{mode==="register"&&<><label htmlFor="nickname">游戏昵称（选填）</label><Input id="nickname" name="name" maxLength={16} placeholder="朋友们怎么称呼你"/></>}{error&&<p role="alert" className="form-error">{error}</p>}<Button disabled={busy} type="submit" className="primary-button">{busy?"正在处理…":mode==="login"?"登录，准备入座":setup?"设置密码，进入后台":"创建账号"}<ArrowRight size={18}/></Button></form><p className="privacy-note"><LockKeyhole size={15}/> 账号只用于游戏与保存对局记录</p><div className="house-rules"><span className="small-caps">本桌规矩</span><p>斗地主 · 四人麻将 · 娱乐积分</p><span>不涉及现金，输赢都图个开心。</span></div></div><footer>娱乐中心 <span>好玩，也好好相处。</span></footer></section></main>
}
