"use client";
import {useEffect,useState} from 'react';
import {Check,ChevronLeft,ChevronRight,LockKeyhole,Timer} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Select,SelectContent,SelectItem,SelectTrigger,SelectValue} from '@/components/ui/select';
import {RadioGroup,RadioGroupItem} from '@/components/ui/radio-group';
import {Pagination,PaginationContent,PaginationItem} from '@/components/ui/pagination';
import {MahjongTile} from '@/components/mahjong-tile';
import {api} from '@/lib/client';
import {typeName,type WinPlan,type Fan} from '@/lib/mahjong/solver';
import {chips} from '@/lib/mahjong/report';
type Options={round:string;total:number;allTotal:number;page:number;pageSize:number;wildTiles:number[];plans:WinPlan[];fans:Fan[]};
export function PlanTiles({groups}:{groups:{kind:string;types:number[];wild:boolean[];incoming:number;exposed?:boolean}[]}){return <div className="ham-plan-tiles">{groups.map((g,i)=><span className={`ham-plan-group ${g.exposed?'is-exposed':''}`} key={i}>{g.types.map((t,j)=><span className={g.incoming===j?'plan-incoming':''} key={j}><MahjongTile tile={t*4} small represented={g.wild[j]}/></span>)}</span>)}</div>}
export function WinPicker({code,round,seconds,busy,onConfirm}:{code:string;round:string;seconds:number;busy:boolean;onConfirm:(id:string)=>void}){
 const [targets,setTargets]=useState(['all','all','all','all']);
 const [data,setData]=useState<Options|null>(null),[page,setPage]=useState(0),[fan,setFan]=useState('all'),[target,setTarget]=useState('all'),[selected,setSelected]=useState<WinPlan|null>(null),[error,setError]=useState(''),[loading,setLoading]=useState(false),[open,setOpen]=useState(true);
 useEffect(()=>{let active=true;setLoading(true);setError('');setSelected(null);api(`/api/mahjong/win-options?room=${code}&page=${page}${fan==='all'?'':'&fan='+fan}${target==='all'?'':'&target='+target}${targets.every(t=>t==='all')?'':'&targets='+targets.filter(t=>t!=='all').join(',')}`).then(d=>{if(active&&d.round===round)setData(d)}).catch(e=>{if(active)setError(e.message)}).finally(()=>{if(active)setLoading(false)});return()=>{active=false};},[code,round,page,fan,target,targets.join(',')]);
 return <><Button className="mj-hu" onClick={()=>setOpen(true)}>选择胡牌方案{!open&&` · ${seconds} 秒`}</Button><Dialog open={open} onOpenChange={setOpen}><DialogContent className="ham-picker"><DialogHeader><div className="ham-picker-eyebrow"><span>胡 牌 方 案</span><span><Timer size={15}/>{seconds} 秒</span></div><DialogTitle>选择胡牌方案</DialogTitle><DialogDescription>选定一套，再翻奖牌。</DialogDescription></DialogHeader>
 <div className="ham-picker-filters"><Select value={fan} onValueChange={v=>{setFan(v);setPage(0)}}><SelectTrigger aria-label="按牌型筛选"><SelectValue placeholder="所有牌型"/></SelectTrigger><SelectContent><SelectItem value="all">所有牌型</SelectItem>{data?.fans.map(f=><SelectItem key={f.id} value={f.id}>{f.name}</SelectItem>)}</SelectContent></Select><Select value={target} onValueChange={v=>{setTarget(v);setPage(0)}}><SelectTrigger aria-label="按赖子代表牌筛选"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="all">赖子代表任意牌</SelectItem>{Array.from({length:34},(_,t)=><SelectItem key={t} value={String(t)}>包含赖子代表 {typeName(t)}</SelectItem>)}</SelectContent></Select></div>
 {data?.wildTiles.length===4&&<div className="ham-multi-targets"><span>指定想要的代表牌 · 可选同种牌，未指定的不限</span><div>{targets.map((value,i)=><Select key={i} value={value} onValueChange={v=>{setTargets(old=>old.map((t,j)=>j===i?v:t));setPage(0)}}><SelectTrigger aria-label={`赖子目标牌${i+1}`}><SelectValue/></SelectTrigger><SelectContent><SelectItem value="all">目标 {i+1} 不限</SelectItem>{Array.from({length:34},(_,t)=><SelectItem key={t} value={String(t)}>{typeName(t)}</SelectItem>)}</SelectContent></Select>)}</div></div>}
 <div className="ham-picker-count">{loading?'正在读取方案…':`共 ${data?.allTotal??0} 套胡牌方案${fan!=='all'||target!=='all'||targets.some(t=>t!=='all')?` · 符合筛选 ${data?.total??0} 套`:''}`}</div>{error&&<p className="form-error" role="alert">{error}</p>}
 <RadioGroup disabled={loading||busy} className="ham-plan-list" value={selected?.id??''} onValueChange={id=>setSelected(data?.plans.find(p=>p.id===id)??null)} aria-label="选择胡牌方案">{data?.plans.map((p,i)=><label className={`ham-plan-card ${selected?.id===p.id?'is-chosen':''}`} htmlFor={`plan-${page}-${i}`} key={p.id}><div className="ham-plan-card-top"><RadioGroupItem id={`plan-${page}-${i}`} value={p.id}/><b>{({standard:'四组牌 + 一对将',seven:'七对',orphans:'十三幺',gates:'九莲宝灯',fourWild:'四赖直胡 · 按牌张组成'})[p.family]}</b><strong>× {chips(p.multiplier)}</strong></div><PlanTiles groups={p.groups}/>{p.family==='fourWild'&&<p className="ham-plan-assignments">此方案不要求成型；七对、碰碰胡等结构类倍数只在对应成型方案中计算。</p>}<div className="ham-fans">{p.fans.map(f=><span key={f.id}>{f.name} ×{f.multiplier}</span>)}</div><p className="ham-plan-assignments">{p.assignments.length?p.assignments.map((a,j)=>`赖${j+1} → ${typeName(a.type)}`).join('　'):'本手无赖子'}</p><p className="ham-hit-types"><span>奖牌可命中</span>{p.hitTypes.map(typeName).join('、')}</p></label>)}</RadioGroup>
 {!loading&&!data?.total&&<p className="muted">这个筛选下没有方案，请换一种代表牌或牌型。</p>}
 <Pagination><PaginationContent><PaginationItem><Button variant="outline" size="sm" disabled={loading||!page} onClick={()=>setPage(p=>p-1)}><ChevronLeft size={15}/>上一页</Button></PaginationItem><PaginationItem><span className="ham-page-count">{(data?.page??page)+1} / {Math.max(1,Math.ceil((data?.total??0)/12))}</span></PaginationItem><PaginationItem><Button variant="outline" size="sm" disabled={loading||!data||(page+1)*12>=data.total} onClick={()=>setPage(p=>p+1)}>下一页<ChevronRight size={15}/></Button></PaginationItem></PaginationContent></Pagination>
 <div className="ham-picker-confirm"><p><LockKeyhole size={15}/>确认后不可更改。超时采用最高倍数；同倍数按固定顺序。</p><Button disabled={busy||loading||!selected||seconds<=0} onClick={()=>selected&&onConfirm(selected.id)}><Check size={17}/>{selected?`确认这套 · ${chips(selected.multiplier)} 倍`:'请先选择一套方案'}</Button></div></DialogContent></Dialog></>;
}
