"use client";
import {useCallback,useEffect,useRef,useState} from 'react';
import {MessageCircle,Send,X} from 'lucide-react';
import {api} from '@/lib/client';
import {Button} from './ui/button';
type Message={id:number;name:string;text:string;created:number;own:number};
export function RoomChat({code,closed=false}:{code:string;closed?:boolean}){
 const [open,setOpen]=useState(false),[messages,setMessages]=useState<Message[]>([]),[draft,setDraft]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[seen,setSeen]=useState(0);
 const openRef=useRef(open),list=useRef<HTMLDivElement>(null),atBottom=useRef(true),initialized=useRef(false),pending=useRef<{id:string;text:string}|null>(null),input=useRef<HTMLTextAreaElement>(null);openRef.current=open;
 const load=useCallback(async()=>{const data=await api('/api/chat?room='+code);setMessages(prev=>(prev.at(-1)?.id||0)>(data.messages.at(-1)?.id||0)?prev:data.messages);const last=data.messages.at(-1)?.id||0;if(!initialized.current||openRef.current)setSeen(prev=>Math.max(prev,last));initialized.current=true;},[code]);
 useEffect(()=>{let live=true,loading=false;async function poll(){if(!live||loading||document.hidden)return;loading=true;try{await load();}catch(e){if(live)setError((e as Error).message);}finally{loading=false;}}void poll();const timer=setInterval(poll,3000);return()=>{live=false;clearInterval(timer);};},[load]);
 useEffect(()=>{if(open){setSeen(messages.at(-1)?.id||0);if(atBottom.current)list.current?.scrollTo({top:list.current.scrollHeight});}},[open,messages]);
 useEffect(()=>{if(open){atBottom.current=true;list.current?.scrollTo({top:list.current.scrollHeight});input.current?.focus();}const escape=(e:KeyboardEvent)=>{if(e.key==='Escape')setOpen(false)};if(open)document.addEventListener('keydown',escape);return()=>document.removeEventListener('keydown',escape)},[open]);
 async function send(){const text=draft.trim();if(!text||busy||closed)return;setBusy(true);setError('');if(!pending.current||pending.current.text!==text)pending.current={id:crypto.randomUUID(),text};try{await api('/api/chat',{code,text,clientId:pending.current.id});pending.current=null;setDraft('');atBottom.current=true;await load();input.current?.focus();}catch(e){setError((e as Error).message);}finally{setBusy(false)}}
 const unread=messages.filter(m=>m.id>seen&&!m.own).length;
 return <div className="room-chat"><Button className="chat-launch" variant="outline" aria-label={`房间聊天${unread?'，'+unread+' 条新消息':''}`} aria-expanded={open} onClick={()=>{setOpen(!open);setError('')}}><MessageCircle size={18}/><span>房间聊天</span>{unread>0&&<b>{unread>9?'9+':unread}</b>}</Button>{open&&<section className="chat-panel" role="dialog" aria-label="房间聊天"><header><div><b>同桌聊两句</b><span>仅本房间玩家可见 · 最近 80 条</span></div><Button variant="ghost" size="icon" aria-label="收起聊天" onClick={()=>setOpen(false)}><X size={18}/></Button></header><div className="chat-messages" ref={list} role="log" aria-live="polite" aria-relevant="additions" onScroll={()=>{if(list.current)atBottom.current=list.current.scrollHeight-list.current.scrollTop-list.current.clientHeight<45;}}>{messages.length?messages.map(m=><article key={m.id} className={m.own?'is-own':''}><div><b>{m.own?'你':m.name}</b><time>{new Date(m.created).toLocaleTimeString('zh-CN',{hour:'2-digit',minute:'2-digit'})}</time></div><p>{m.text}</p></article>):<div className="chat-empty"><MessageCircle size={30}/><p>跟朋友打个招呼吧。</p><span>机器人不会参与聊天。</span></div>}</div>{error&&<p className="chat-error" role="alert">{error}</p>}<form onSubmit={e=>{e.preventDefault();void send()}}><textarea ref={input} aria-label="聊天内容" placeholder={closed?'牌桌已结束，聊天记录只读':'说点什么…'} maxLength={500} value={draft} disabled={closed} onChange={e=>setDraft(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'&&!e.shiftKey&&!e.nativeEvent.isComposing&&e.nativeEvent.keyCode!==229){e.preventDefault();void send();}}}/><div><small>{draft.length} / 500 · Enter 发送</small><Button type="submit" disabled={busy||closed||!draft.trim()}><Send size={14}/>{busy?'发送中':'发送'}</Button></div></form></section>}</div>;
}
