"use client";
import {RoomCodeCopy} from '@/components/room-code-copy';
import {useSearchParams} from 'next/navigation';
import {useClub,useClubState,useRoomNavigation,HistoryEntry} from '@/components/club-provider';
import {useCallback,useEffect,useRef,useState,type CSSProperties} from 'react';
import {Club,ArrowLeft,Plus,Users,Timer,Copy,Settings,LogOut,History,Bot,Coins} from 'lucide-react';
import {Button} from '@/components/ui/button';import {Input} from '@/components/ui/input';import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription,DialogTrigger} from '@/components/ui/dialog';
import AuthScreen from '@/components/auth-screen';import {Card} from '@/components/poker-table';import {GameNav} from '@/components/game-nav';import {RoomMode} from '@/components/room-mode';import {RoomChat} from '@/components/room-chat';import {PlayerChat,useChatBubbles} from '@/components/player-chat';import {TableSound} from '@/components/table-sound';import {HoldemRulesGuide} from '@/components/holdem-rules';
import {api} from '@/lib/client';import {holdemRules,type HoldemView,type HoldemResult} from '@/lib/holdem/engine';
import {chips} from '@/lib/mahjong/report';
type User={id:string;name:string;role:string;score:number};type Room={code:string;title:string;revision:number;serverNow:number;receivedAt:number;game:HoldemView};
type Lobby={activeRoom?:string;activeKind?:string;config:{seconds:number;announcement:string;maintenance:boolean};records:{room_code:string;result:HoldemResult}[];tables:{code:string;title:string;rounds:number;ended:number;net:string;brought:string;stack:string}[]};
const streetName={preflop:'翻牌前',flop:'翻牌',turn:'转牌',river:'河牌'};
export default function Holdem(){
 const {user,setUser,loaded,lobby,loadLobby}=useClub(),search=useSearchParams();
 const {openRoom,followRoom}=useRoomNavigation();

 const [room,setRoom]=useClubState<Room|null>('holdem:room',null);
 const [busy,setBusy]=useState(false),[error,setError]=useState(''),[clock,setClock]=useState(Date.now()),[create,setCreate]=useState(false),[code,setCode]=useClubState('holdem:code',''),[title,setTitle]=useClubState('holdem:title',''),[capacity,setCapacity]=useClubState('holdem:capacity',6),[mode,setMode]=useClubState('holdem:mode','friends'),[initial,setInitial]=useClubState('holdem:initial','1000'),[ante,setAnte]=useClubState('holdem:ante','10'),[small,setSmall]=useClubState('holdem:small','20'),[big,setBig]=useClubState('holdem:big','30'),[seconds,setSeconds]=useClubState('holdem:seconds',30),[raise,setRaise]=useClubState('holdem:raise',''),[copied,setCopied]=useState(false),[ending,setEnding]=useState(false);
 const tableScroll=useRef<HTMLDivElement>(null);
 useEffect(()=>{const el=tableScroll.current;if(!el)return;const center=()=>{el.scrollLeft=Math.max(0,(el.scrollWidth-el.clientWidth)/2)};center();const resize=new ResizeObserver(center);resize.observe(el);return()=>resize.disconnect()},[room?.code]);
 const ref=useRef(room);ref.current=room;const {bubbles,onSnapshot}=useChatBubbles(room?.code,user?.id);
 const accept=useCallback((r:Room)=>{setRoom(old=>!old||old.code!==r.code||r.revision>=old.revision?{...r,receivedAt:Date.now()}:old)},[setRoom]);
 const load=loadLobby;
 useEffect(()=>{const requested=search.get('room');if(requested&&/^\d{6}$/.test(requested))setCode(requested);},[search,setCode]);
 useEffect(()=>{void loadLobby().catch(e=>setError(e.message));},[loadLobby]);
 const [secondsInitialized,setSecondsInitialized]=useClubState('holdem:secondsInitialized',false);
 useEffect(()=>{if(lobby&&!secondsInitialized){setSeconds(lobby.config.seconds);setSecondsInitialized(true)}},[lobby,secondsInitialized,setSeconds,setSecondsInitialized]);
 useEffect(()=>{const id=setInterval(()=>setClock(Date.now()),250);return()=>clearInterval(id)},[]);
 useEffect(()=>{if(!room?.code)return;let active=true,pending=false;const poll=async()=>{if(pending)return;pending=true;try{const d=await api('/api/holdem?room='+room.code);if(active&&ref.current?.code===room.code)accept(d)}catch(e){if(active){setError((e as Error).message);if((e as any).status===401)setUser(null);else if((e as any).status===403){setRoom(null);void loadLobby(true).catch(()=>{})}}}finally{pending=false}};void poll();const id=setInterval(poll,1000);return()=>{active=false;clearInterval(id)}},[room?.code,accept,setUser,setRoom,loadLobby]);
 const g=room?.game,seat=g?.seats.findIndex(s=>s.id===user?.id)??-1,me=g?.seats[seat],o=g?.options;
 const remaining=room?Math.max(0,Math.ceil((room.game.deadline-clock-room.serverNow+room.receivedAt)/1000)):0;
 const raiseKey=[g?.round,g?.street,g?.turn,o?.minRaise].join(':');const [raiseWindow,setRaiseWindow]=useClubState('holdem:raiseWindow','');
 useEffect(()=>{if(raiseKey!==raiseWindow){setRaise(o?.minRaise||'');setRaiseWindow(raiseKey)}},[raiseKey,raiseWindow,o?.minRaise,setRaise,setRaiseWindow]);
 async function act(action:string,extra:Record<string,unknown>={}){if(busy)return;setBusy(true);setError('');try{const r=ref.current,d=await api('/api/holdem',{action,code:r?.code||code,revision:r?.revision,...extra});if(d.redirect){await followRoom(d.redirect);return;}if(d.left){setRoom(null);await load(true)}else accept(d);if(['create','join','end_table','end_practice'].includes(action)||d.game?.phase==='finished')await loadLobby(true);setCreate(false);setEnding(false);}catch(e){setError((e as Error).message);if((e as {status?:number}).status===409&&ref.current)api('/api/holdem?room='+ref.current.code).then(accept).catch(()=>{});}finally{setBusy(false)}}
 async function resume(){if(!lobby?.activeRoom||!lobby.activeKind)return;setBusy(true);try{await openRoom(lobby.activeKind,lobby.activeRoom)}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 if(!loaded)return <main className="mj-loading">正在打开德州牌桌…</main>;if(!user)return <AuthScreen onAuth={setUser}/>;
 return <div className="app-shell th-shell"><div className="club-game-tools"><TableSound room={room?{...room,game:{...room.game,options:undefined}}:null} userId={user.id} seconds={remaining}/><HoldemRulesGuide rules={g?.rules??holdemRules()}/></div>
 {error&&<div className="th-error" role="alert">{error}<button onClick={()=>setError('')}>×</button></div>}
 {!room||!g?<main className="th-lobby"><div className="th-lobby-top"><span>03 / POKER</span><h1>德州扑克</h1><p>留两个位置：一份好牌，一桌朋友。</p></div><section className="th-entry"><div className="th-entry-copy"><div className="th-pills"><span>4–10 人</span><span>无限注</span><span>独立娱乐筹码</span></div><h2>今晚，谁拿下底池？</h2><p>自选座位数、前注和盲注。朋友不足时，让陪练来补位。</p>{lobby?.activeRoom?<Button onClick={resume}>返回当前房间 {lobby.activeRoom}</Button>:<Button onClick={()=>setCreate(true)} disabled={!lobby||lobby.config.maintenance}><Plus size={18}/>开一桌德州</Button>}</div><div className="th-entry-cards"><Card card={44}/><Card card={45}/><span>两张底牌，无数种可能。</span></div></section><form className="th-join" onSubmit={e=>{e.preventDefault();void act('join')}}><label htmlFor="th-code">朋友已经开桌？</label><Input id="th-code" aria-label="德州房间号" placeholder="6 位房间号" value={code} onChange={e=>setCode(e.target.value)} maxLength={6}/><Button disabled={busy||!/^\d{6}$/.test(code)}>入座</Button></form>{lobby?.config.announcement&&<p className="th-notice">{lobby.config.announcement}</p>}<HistoryEntry game="holdem"/></main>:<main className="th-room"><div className="th-room-heading"><Button variant="ghost" size="icon" aria-label="返回德州大厅" onClick={()=>{setRoom(null);void load(true)}}><ArrowLeft size={20}/></Button><div><h1>{room.title}</h1><p>房间 {room.code}<RoomCodeCopy code={room.code} compact/> · {g.rules.capacity} 人 · 前注 {chips(g.rules.ante)} · 盲注 {chips(g.rules.small)} / {chips(g.rules.big)}</p></div><Button variant="outline" onClick={()=>navigator.clipboard.writeText(location.origin+'/holdem?room='+room.code).then(()=>{setCopied(true);setTimeout(()=>setCopied(false),2000)}).catch(()=>setError('请把房间号 '+room.code+' 发给朋友'))}><Copy size={16}/>{copied?'已复制':'邀请朋友'}</Button></div><p className="th-scroll-hint">左右滑动查看完整牌桌，操作区始终在下方。</p>
 <div ref={tableScroll} className="th-table-scroll"><section className="th-table" aria-label={`${g.rules.capacity} 人德州牌桌`}><div className="th-felt"/><div className="th-table-number">第 {g.roundNumber||'—'} 手 · {g.seats.length}/{g.rules.capacity} 人</div><div className="th-center"><span className="th-street">{g.phase==='waiting'?'等朋友入座':g.phase==='finished'?'本手已结算':g.phase==='closed'?'整桌已结束':streetName[g.street]}</span><div className="th-pot"><Coins size={20}/><span>{['finished','closed'].includes(g.phase)?'本手总投入':'底池'} <b>{chips(g.pot)}</b></span></div><div className="th-community" aria-label="公共牌">{Array.from({length:5},(_,i)=>g.board[i]!==undefined?<Card key={i} card={g.board[i]}/>:<span key={i} className="th-card-placeholder">{i<3?'F':i===3?'T':'R'}</span>)}</div>{g.phase==='waiting'?<p>坐满并准备后开局<br/><small>房主可在空位添加人机</small></p>:g.phase==='runout'?<p>已全下 · 正在依次翻公共牌</p>:g.phase==='playing'?<p>{g.seats[g.turn]?.name} 正在行动</p>:g.result&&<p>{g.result.type==='aborted'?'本手中止 · 下注已退回':g.result.type==='fold'?'其余玩家弃牌，无需摊牌':'按最佳五张分配各个底池'}</p>}</div>
 {Array.from({length:g.rules.capacity},(_,relative)=>{const index=(Math.max(seat,0)+relative)%g.rules.capacity,s=g.seats[index],a=Math.PI/2+relative*Math.PI*2/g.rules.capacity,style={'--x':`${50+42*Math.cos(a)}%`,'--y':`${50+38*Math.sin(a)}%`} as CSSProperties,r=g.result?.seats[index];return <section key={s?.id??index} style={style} className={`th-seat ${g.turn===index&&g.phase==='playing'?'is-turn':''} ${s?.folded?'is-folded':''} ${index===seat?'is-me':''}`} aria-label={(s?.name||'空位')+'的座位'}>{s?<><PlayerChat bubble={bubbles[s.id]} align="center"><span className="avatar">{s.name.slice(0,1)}</span></PlayerChat><b className="th-player-name" title={s.name}>{s.name}{index===seat?' · 你':''}{s.bot&&<small>人机</small>}</b><div className="th-position">{g.button===index&&<em>D</em>}{g.smallSeat===index&&<span>小盲</span>}{g.bigSeat===index&&<span>大盲</span>}</div><strong className="th-stack">{chips(s.stack)}<small>筹码</small></strong><div className="th-hole" aria-label={s.name+'的底牌'}>{s.hand.length?s.hand.map(c=><Card key={c} card={c} small/>):[0,1].map(i=><span className="th-card-back" key={i}/>)}</div>{g.phase==='playing'&&g.turn===index?<span className="th-clock"><Timer size={13}/>{Math.min(g.rules.seconds,remaining)} 秒</span>:<span className="th-seat-action">{g.phase==='closed'?'本桌结束':['waiting','finished'].includes(g.phase)?s.ready?'已准备':'等待准备':s.last||'等待行动'}</span>}{['playing','runout'].includes(g.phase)&&s.bet!=='0'&&<span className="th-bet">本轮 {chips(s.bet)}</span>}{r&&<span className={BigInt(r.delta)>=0n?'positive':'negative'}>{r.value?.name} {chips(r.delta,true)}</span>}{s.bot&&!g.fixed&&g.host===user.id&&<button className="th-remove" disabled={busy} onClick={()=>act('remove_bot',{botId:s.id})}>移除人机</button>}</>:<div className="th-empty"><Users size={26}/><span>等一位朋友</span>{g.host===user.id&&!g.fixed&&<Button size="sm" variant="outline" disabled={busy} onClick={()=>act('add_bot')}><Bot size={14}/>添加人机</Button>}</div>}</section>})}</section></div>
 <section className="th-controls"><div className="th-own"><div className="th-own-cards">{me?.hand.map(c=><Card card={c} key={c} small/>)}</div><div><b>{me?.name}</b><span>筹码 {chips(me?.stack??'0')} · 累计带入 {chips(me?.brought??'0')}</span></div></div>{o?.acting?<div className="th-actions"><Button variant="outline" disabled={busy} onClick={()=>act('fold')}>弃牌</Button><Button disabled={busy} onClick={()=>act(o.check?'check':'call')}>{o.check?'过牌':'跟注 '+chips(o.call)}</Button><Button variant="outline" disabled={busy||!o.canAllIn} onClick={()=>act('allin')}>全下 {chips(me?.stack??'0')}</Button><div className="th-raise"><Input aria-label="加注至本轮总额" inputMode="numeric" value={raise} onChange={e=>setRaise(e.target.value)} disabled={!o.canRaise||busy}/><Button disabled={!o.canRaise||busy} onClick={()=>act('raise',{amount:raise})}>加注至</Button><small>至少 {chips(o.minRaise)} · 最多 {chips(o.maxRaise)}</small></div></div>:['waiting','finished'].includes(g.phase)?<div className="th-actions">{me?.stack==='0'?<Button disabled={busy} onClick={()=>act('rebuy')}>补入 {chips(g.rules.initial)} 筹码</Button>:<Button disabled={busy} onClick={()=>act('ready')}>{me?.ready?'取消准备':'准备好了'}</Button>}<span>{g.seats.filter(s=>s.ready).length}/{g.rules.capacity} 人准备</span></div>:<span className="th-controls-status">{g.phase==='closed'?'整桌已结束':me?.folded?'本手已弃牌，等待下一手':g.phase==='runout'?'正在翻公共牌':'等待其他牌友行动'}</span>}</section>
 <div className="th-tools"><HoldemRulesGuide rules={g.rules}/><Dialog><DialogTrigger asChild><Button variant="outline"><History size={16}/>牌桌记录</Button></DialogTrigger><DialogContent className="th-rules"><DialogHeader><DialogTitle>本桌收支与记录</DialogTitle><DialogDescription>净输赢已扣除累计带入；补筹码不算赢分。</DialogDescription></DialogHeader><table className="th-summary"><thead><tr><th>玩家</th><th>累计带入</th><th>结余</th><th>净输赢</th></tr></thead><tbody>{g.seats.map(s=><tr key={s.id}><td>{s.name}</td><td>{chips(s.brought)}</td><td>{chips(s.stack)}</td><td>{chips(s.net,true)}</td></tr>)}</tbody></table>{g.result&&<ResultDetails result={g.result}/>}<details><summary>本手操作记录</summary>{g.log.map((l,i)=><p key={i}>{l.text}</p>)}</details></DialogContent></Dialog>{!g.fixed&&g.phase==='waiting'&&<Button variant="ghost" onClick={()=>act('leave')}>离开房间</Button>}{g.host===user.id&&['waiting','finished'].includes(g.phase)&&<Button variant="ghost" onClick={()=>setEnding(true)}>结束整桌</Button>}{g.phase==='closed'&&<Button onClick={()=>{setRoom(null);void load(true)}}>返回大厅</Button>}</div><RoomChat key={room.code} userId={user.id} closed={g.phase==='closed'} code={room.code} onSnapshot={onSnapshot}/></main>}
 <Dialog open={create} onOpenChange={setCreate}><DialogContent className="th-create"><DialogHeader><DialogTitle>开一桌德州扑克</DialogTitle><DialogDescription>设置在建房后固定，整桌使用同一套规则。</DialogDescription></DialogHeader><form className="th-form" onSubmit={e=>{e.preventDefault();void act('create',{title,capacity,initial,ante,small,big,seconds,mode})}}><label>房间名称<Input value={title} onChange={e=>setTitle(e.target.value)} maxLength={24} placeholder={user.name+' 的德州桌'}/></label><div className="th-form-grid"><label>座位数<select value={capacity} onChange={e=>setCapacity(Number(e.target.value))}>{Array.from({length:7},(_,i)=><option key={i} value={i+4}>{i+4} 人</option>)}</select></label><label>每人初始筹码<Input value={initial} inputMode="numeric" onChange={e=>setInitial(e.target.value)}/></label><label>每人前注<Input value={ante} inputMode="numeric" onChange={e=>setAnte(e.target.value)}/></label><label>小盲<Input value={small} inputMode="numeric" onChange={e=>setSmall(e.target.value)}/></label><label>大盲<Input value={big} inputMode="numeric" onChange={e=>setBig(e.target.value)}/></label><label>操作时限<select value={seconds} onChange={e=>setSeconds(Number(e.target.value))}>{[15,30,45,60].map(s=><option value={s} key={s}>{s} 秒</option>)}</select></label></div><RoomMode mode={mode} onChange={setMode} bots={capacity-1} betweenHandsOnly/><p>固定盲注 · 无限注 · 无抽水<br/>输光后可在局间补入初始筹码，累计带入单独记录。</p><>{error&&<p role="alert" className="form-error">{error}</p>}</><Button disabled={busy} type="submit"><Plus size={17}/>创建 {capacity} 人房</Button></form></DialogContent></Dialog>
 <Dialog open={ending} onOpenChange={setEnding}><DialogContent><DialogHeader><DialogTitle>结束这桌德州扑克？</DialogTitle><DialogDescription>保留已完成的结算，所有玩家可重新建房。</DialogDescription></DialogHeader><Button disabled={busy} onClick={()=>act('end_table')}>确认结束整桌</Button></DialogContent></Dialog></div>;
}
function ResultDetails({result:r}:{result:HoldemResult}){return <section className="th-result-detail"><h3>第 {r.roundNumber} 手 · {r.type==='aborted'?'本手中止':r.type==='fold'?'无需摊牌':'摊牌结果'}</h3><div className="th-report-board">{r.board.map(c=><Card key={c} card={c} small/>)}</div>{r.pots.map((p,i)=><p key={i}><b>{p.refund?'退回未被跟注部分':i===0?'主池':'边池 '+i} {chips(p.amount)}</b><span>{p.winners.map(w=>r.seats[w].name).join('、')}</span></p>)}{r.seats.map(s=><div className="th-report-player" key={s.id}><b>{s.name} <span className={BigInt(s.delta)>=0n?'positive':'negative'}>{chips(s.delta,true)}</span></b>{s.value&&<span>{s.value.name} · 最佳五张</span>}<div>{s.value?.cards.map(c=><Card key={c} card={c} small/>)}</div></div>)}</section>}
