"use client";
import {useCallback,useEffect,useRef,useState} from 'react';
import {ArrowLeft,ArrowRight,Check,ChevronRight,Club,Copy,DoorOpen,History,Info,Layers3,LogOut,Plus,RefreshCw,Settings,ShieldCheck,Timer,Users,X} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogTrigger,DialogDescription} from '@/components/ui/dialog';
import {AlertDialog,AlertDialogContent,AlertDialogHeader,AlertDialogTitle,AlertDialogDescription,AlertDialogFooter,AlertDialogCancel,AlertDialogAction} from '@/components/ui/alert-dialog';
import AuthScreen from '@/components/auth-screen';
import {MahjongTile} from '@/components/mahjong-tile';
import {api} from '@/lib/client';
import {tileLabel,type MahjongView} from '@/lib/mahjong/engine';
import {BASIC_136,RULE_NOTES} from '@/lib/mahjong/rules';

type User={id:string;name:string;username:string;role:string;score:number};
type Room={code:string;title:string;revision:number;serverNow:number;receivedAt:number;game:MahjongView};
type RecordItem={room_code:string;created:number;result:{winner:number;winType:string;seats:{id:string;name:string;delta:number}[]}};
type Lobby={user:User;config:{announcement:string;seconds:number;maintenance:boolean};activeRoom:string|null;activeKind:string|null;records:RecordItem[]};
function Rules(){return <Dialog><DialogTrigger asChild><Button variant="ghost"><Info size={17}/><span className="hide-small">本桌规则</span></Button></DialogTrigger><DialogContent className="rules-modal"><DialogHeader><DialogTitle>136 张 · 基础试玩</DialogTitle><DialogDescription>按这张牌桌的约定来玩，细则会在后续逐步完善。</DialogDescription></DialogHeader><div className="rules-list">{RULE_NOTES.map(([title,text])=><p key={title}><b>{title}</b>{text}</p>)}</div></DialogContent></Dialog>}
function Avatar({name,index=0}:{name:string;index?:number}){return <span className={`avatar avatar-${index%3}`}>{name.slice(0,1).toUpperCase()}</span>}
function Seat({player,index,active,dealer,position}:{player?:MahjongView['seats'][number];index:number;active:boolean;dealer:boolean;position:string}){return <div className={`mj-seat ${position} ${active?'is-active':''}`}>
 {player?<><Avatar name={player.name} index={index}/><div className="mj-seat-info"><b>{player.name}{dealer&&<em>庄</em>}</b><span>{player.count?`${player.count} 张手牌`:player.ready?'已准备':'未准备'}</span></div><small>{player.last||'已入座'}</small>{player.count>0&&<div className="mj-concealed-count" aria-hidden="true">{Array.from({length:Math.min(player.count,8)},(_,i)=><i key={i}/>)}</div>}</>:<><span className="mj-empty-avatar"><Plus size={21}/></span><div className="mj-seat-info"><b>等一位朋友</b><span>座位空闲</span></div></>}
 </div>}
export default function MahjongPage(){
 const [user,setUser]=useState<User|null>(null),[loaded,setLoaded]=useState(false),[lobby,setLobby]=useState<Lobby|null>(null),[room,setRoom]=useState<Room|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[code,setCode]=useState(''),[title,setTitle]=useState(''),[createOpen,setCreateOpen]=useState(false),[leaveOpen,setLeaveOpen]=useState(false),[selected,setSelected]=useState<number|null>(null),[clock,setClock]=useState(Date.now()),[copied,setCopied]=useState(false);
 const roomRef=useRef<Room|null>(null);roomRef.current=room;
 const accept=useCallback((next:Room)=>setRoom(prev=>!prev||prev.code!==next.code||next.revision>=prev.revision?{...next,receivedAt:Date.now()}:prev),[]);
 const fail=useCallback((e:Error&{status?:number})=>{setError(e.message);if(e.status===401){setUser(null);setRoom(null)}},[]);
 const loadLobby=useCallback(async()=>{const d=await api('/api/mahjong');setLobby(d);setUser(d.user);return d;},[]);
 useEffect(()=>{const requested=new URLSearchParams(location.search).get('room');if(requested&&/^\d{6}$/.test(requested))setCode(requested);api('/api/auth').then(d=>setUser(d.user)).catch(e=>setError(e.message)).finally(()=>setLoaded(true));},[]);
 useEffect(()=>{if(user?.id)loadLobby().catch(fail)},[user?.id,loadLobby,fail]);
 useEffect(()=>{if(!room?.code)return;let active=true,pending=false;const current=room.code;const poll=async()=>{if(pending)return;pending=true;try{const d=await api('/api/mahjong?room='+current);if(active&&roomRef.current?.code===current){accept(d);setError('')}}catch(e){if(active)fail(e as Error)}finally{pending=false}};const id=setInterval(poll,1500);return()=>{active=false;clearInterval(id)};},[room?.code,accept,fail]);
 useEffect(()=>{const id=setInterval(()=>setClock(Date.now()),300);return()=>clearInterval(id)},[]);
 const g=room?.game,seat=g?.seats.findIndex(s=>s.id===user?.id)??-1,me=g?.seats[seat];
 useEffect(()=>setSelected(null),[me?.hand.join(',')]);
 useEffect(()=>{if(g?.phase==='finished')loadLobby().catch(fail)},[g?.phase,loadLobby,fail]);
 async function act(action:string,extra:Record<string,unknown>={}){if(busy)return;setBusy(true);setError('');try{const r=roomRef.current,d=await api('/api/mahjong',{action,code:r?.code||code,revision:r?.revision,...extra});if(d.redirect){location.assign(d.redirect);return;}if(d.left){setRoom(null);await loadLobby()}else accept(d);setCreateOpen(false);setLeaveOpen(false);}catch(e){fail(e as Error);if((e as {status?:number}).status===409&&roomRef.current){api('/api/mahjong?room='+roomRef.current.code).then(accept).catch(fail)}}finally{setBusy(false)}}
 async function resume(){if(lobby?.activeKind==='landlord'){location.assign('/?room='+lobby.activeRoom);return;}setBusy(true);try{accept(await api('/api/mahjong?room='+lobby?.activeRoom))}catch(e){fail(e as Error)}finally{setBusy(false)}}
 async function copy(){try{await navigator.clipboard.writeText(`${location.origin}/mahjong?room=${room!.code}`);setCopied(true);setTimeout(()=>setCopied(false),2000)}catch{setError('请把房间号 '+room!.code+' 发给朋友')}}
 if(!loaded)return <main className="mj-loading"><span className="brand-icon"><Club size={22}/></span><p>正在打开游戏室…</p></main>;
 if(!user)return <><AuthScreen onAuth={setUser}/>{error&&<div className="floating-error" role="alert">{error}<button onClick={()=>location.reload()}>重试</button></div>}</>;
 const offset=room?room.serverNow-room.receivedAt:0,seconds=g?Math.max(0,Math.ceil((g.deadline-clock-offset)/1000)):0;
 const myTurn=g?.phase==='playing'&&!g.pending&&g.turn===seat,ownTiles=me?[...me.hand.filter(t=>t!==g?.drawn),...(g?.drawn!==null&&g?.drawn!==undefined&&me.hand.includes(g.drawn)?[g.drawn]:[])]:[];
 const status=g?.phase==='waiting'?g.seats.length===4?'四人已到齐，准备开局':'等朋友入座':g?.phase==='closed'?'房间已关闭':g?.phase==='finished'?g.winType==='draw'?'本局流局':`${g.seats[g.winner].name} ${g.winType==='self'?'自摸':'胡牌'}`:g?.pending?(g.options.canPass?'轮到你响应这张牌':'等待吃碰杠胡选择'):myTurn?'轮到你出牌':`等待 ${g?.seats[g.turn].name} 出牌`;
 return <div className="app-shell mj-shell"><header className="app-header"><a href="/" className="brand"><span className="brand-icon"><Club size={21}/></span><span>娱乐中心<small>好 友 游 戏 室</small></span></a><nav className="game-nav" aria-label="选择游戏"><a href="/">斗地主</a><a href="/mahjong" aria-current="page">麻将</a></nav><div className="header-right"><Rules/>{user.role==='admin'&&<Button variant="ghost" size="icon" asChild><a href="/admin" aria-label="管理后台"><Settings size={18}/></a></Button>}<span className="header-user"><Avatar name={user.name}/><span>{user.name}</span></span><Button variant="ghost" size="icon" aria-label="退出登录" onClick={()=>api('/api/auth',{action:'logout'}).then(()=>{setUser(null);setRoom(null);setLobby(null)})}><LogOut size={18}/></Button></div></header>
 {error&&<div className="connection-error" role="alert">{error}<button aria-label="关闭提示" onClick={()=>setError('')}><X size={17}/></button></div>}
 {!room||!g||!me?<main className="mj-lobby"><section className="mj-lobby-main"><div className="lobby-heading"><div className="section-tag">再 聚 一 桌</div><h1>四个人，刚刚好。</h1><p>熟悉的朋友，新的这一局。</p></div>{lobby?.config.announcement&&<div className="announcement"><Info size={17}/><span>{lobby.config.announcement}</span></div>}
 <section className="mj-welcome"><div className="mj-welcome-top"><span className="mj-badge">基础试玩</span><span>02 / MAHJONG</span></div><div className="mj-welcome-body"><div><h2>麻将</h2><p>落一张牌，聊一会儿天。</p><div className="mj-summary"><span><Users size={16}/>四人好友房</span><span>136 张 · 无花牌</span></div>{lobby?.activeRoom?<Button className="mj-start" onClick={resume} disabled={busy}>{lobby.activeKind==='mahjong'?'回到麻将桌':'回到斗地主房间'}<ArrowRight size={18}/></Button>:<Dialog open={createOpen} onOpenChange={setCreateOpen}><DialogTrigger asChild><Button className="mj-start" disabled={!lobby||lobby.config.maintenance}><Plus size={19}/>开一桌麻将</Button></DialogTrigger><DialogContent><DialogHeader><DialogTitle>开一桌麻将</DialogTitle><DialogDescription>创建后把邀请链接发给另外三位朋友。四人都准备好，就会发牌。</DialogDescription></DialogHeader><form className="stack-form" onSubmit={e=>{e.preventDefault();act('create',{title,rulesId:BASIC_136.id})}}><label htmlFor="mj-title">房间名称</label><Input id="mj-title" maxLength={24} value={title} onChange={e=>setTitle(e.target.value)} placeholder={`${user.name} 的麻将桌`}/><div className="mj-room-rules"><b>136 张 · 基础试玩</b><p>不换三张、不定缺 · 可吃碰杠<br/>一人胡牌结束 · 每步 {lobby?.config.seconds||30} 秒</p></div><Button type="submit" disabled={busy}>{busy?'正在开桌…':'创建房间'}</Button></form></DialogContent></Dialog>}</div><div className="mj-intro-tiles" aria-label="万筒条与字牌"><MahjongTile tile={16}/><MahjongTile tile={52}/><MahjongTile tile={88}/><MahjongTile tile={124}/></div></div><div className="mj-welcome-footer"><span>吃 · 碰 · 杠 · 胡</span><span>娱乐积分，轻松开局。</span></div></section>
 <section className="join-box"><div><h3>朋友已经开桌了？</h3><p>输入 6 位房间号，留个位置给自己。</p></div><form onSubmit={e=>{e.preventDefault();act('join')}}><Input aria-label="6 位麻将房间号" placeholder="6 位房间号" inputMode="numeric" pattern="[0-9]{6}" maxLength={6} value={code} onChange={e=>setCode(e.target.value.replace(/\D/g,''))} required/><Button type="submit" disabled={busy||code.length!==6}>入座<ChevronRight size={17}/></Button></form></section>
 <div className="mj-rule-strip"><div><Layers3 size={20}/><b>四组牌，一对将</b><span>从基础胡牌开始</span></div><div><Timer size={20}/><b>按时限自动操作</b><span>掉线后可回到原桌</span></div><div><ShieldCheck size={20}/><b>只记娱乐积分</b><span>之后再细化番数规则</span></div></div>
 </section><aside className="mj-lobby-aside"><div className="profile-card"><Avatar name={user.name}/><h3>{user.name}</h3><span>今天也有好牌运</span><div className="profile-score"><span>总娱乐积分</span><strong>{user.score>0?'+':''}{user.score}</strong></div></div><section className="recent"><h3><History size={17}/>最近麻将对局</h3>{!lobby?<p className="muted">正在读取…</p>:!lobby.records.length?<div className="empty-history"><Layers3 size={30}/><p>第一桌，等你开场。</p><span>胡牌与流局的记录都会留在这里。</span></div>:lobby.records.map((r,i)=>{const p=r.result.seats.find(s=>s.id===user.id)!;return <div className="history-row" key={i}><div><b>{r.result.winType==='draw'?'流局':p.delta>0?'胡了一手好牌':'下局再来'}</b><span>{r.room_code} · {new Date(r.created).toLocaleDateString('zh-CN')}</span></div><strong className={p.delta>=0?'positive':'negative'}>{p.delta>0?'+':''}{p.delta}</strong></div>})}</section><p className="aside-note"><ShieldCheck size={15}/>独立账号 · 只有同桌可见对局</p></aside></main>:
 <main className="mj-room"><div className="room-toolbar"><div><Button variant="ghost" size="icon" aria-label="返回麻将大厅" onClick={()=>{setRoom(null);loadLobby().catch(fail)}}><ArrowLeft size={20}/></Button><div><h2>{room.title}</h2><span>房间 {room.code} · {g.rules.name}</span></div></div><Button variant="outline" onClick={copy}>{copied?<Check size={16}/>:<Copy size={16}/>}<span>{copied?'已复制':'邀请朋友'}</span></Button></div>
 <div className="mj-table-layout"><section className="mj-board" aria-label="四人麻将牌桌"><div className="mj-board-top"><span><Users size={15}/>{g.seats.length} / 4 入座</span><span className="mj-board-label">好 友 麻 将</span><span><Layers3 size={15}/>{g.phase==='waiting'?'136 张牌':`第 ${g.roundNumber} 局`}</span></div>
 <Seat player={g.seats[(seat+2)%4]} index={2} active={g.phase==='playing'&&g.turn===(seat+2)%4&&!g.pending} dealer={g.dealer===(seat+2)%4&&g.phase!=='waiting'} position="mj-seat-north"/>
 <div className="mj-middle"><Seat player={g.seats[(seat+3)%4]} index={1} active={g.phase==='playing'&&g.turn===(seat+3)%4&&!g.pending} dealer={g.dealer===(seat+3)%4&&g.phase!=='waiting'} position="mj-seat-west"/>
 <div className="mj-center">{g.phase==='waiting'?<div className="mj-waiting"><div className="mj-wait-icon"><Layers3 size={29}/></div><span className="section-tag">四 人 一 桌</span><h2>{status}</h2><p>把房间号发给朋友<br/>四人准备后自动发牌</p><div className="mj-room-code">{room.code}</div></div>:g.phase==='closed'?<div className="mj-waiting"><DoorOpen size={33}/><h2>这桌已结束</h2><p>未完成的本局不计分。</p><Button onClick={()=>{setRoom(null);loadLobby().catch(fail)}}>返回大厅</Button></div>:g.phase==='finished'?<div className="mj-results"><div className="section-tag">本 局 结 算</div><h2>{status}</h2><p>{g.winType==='draw'?'牌墙已摸完，本局不计分':g.winType==='self'?'自摸，每位牌友支付 1 分':`${g.seats[g.source].name} ${g.winType==='rob'?'被抢杠':'点炮'}，支付 1 分`}</p><div className="mj-score-grid">{g.seats.map((s,i)=><div key={s.id}><span>{s.name}</span><strong className={g.deltas[i]>=0?'positive':'negative'}>{g.deltas[i]>0?'+':''}{g.deltas[i]}</strong></div>)}</div><p>准备好，再来一局。</p></div>:<><div className="mj-turn-display"><div><span>牌墙剩余</span><strong>{g.remaining}<small>张</small></strong></div><div className="mj-turn-text"><b>{status}</b><span>{g.pending?`${g.seats[g.pending.from].name} ${g.pending.kind==='added'?'补杠':'打出'} ${tileLabel(g.pending.tile)}`:myTurn?'选中手牌，再点击「出牌」':'可以先看看自己的手牌'}</span></div><div className={`mj-countdown ${seconds<=5?'is-urgent':''}`}><Timer size={15}/>{seconds}<small>秒</small></div></div>
 <div className="mj-rivers">{[2,3,1,0].map(off=>{const i=(seat+off)%4,s=g.seats[i];return <div className={`mj-river river-${off}`} key={s.id}><span>{s.name}{i===seat?' · 你':''}<small>{s.river.length} 张</small></span><div>{s.river.length?s.river.map(t=><span className={g.lastDiscard?.tile===t?'latest-tile':''} key={t}><MahjongTile tile={t} small/></span>):<em>尚未出牌</em>}</div>{s.melds.length>0&&<div className="mj-open-melds">{s.melds.map((m,j)=><div key={j}><small>{m.concealed?'暗杠':m.kind==='chi'?'吃':m.kind==='pong'?'碰':'杠'}</small>{(m.concealed&&i!==seat?[0,1,2,3]:m.tiles).map((t,k)=><MahjongTile key={k} tile={t} hidden={m.concealed&&i!==seat} small/>)}</div>)}</div>}</div>})}</div></>}
 </div><Seat player={g.seats[(seat+1)%4]} index={2} active={g.phase==='playing'&&g.turn===(seat+1)%4&&!g.pending} dealer={g.dealer===(seat+1)%4&&g.phase!=='waiting'} position="mj-seat-east"/></div>
 <div className={`mj-self ${myTurn?'is-my-turn':''}`}><div className="mj-self-top"><div><Avatar name={me.name}/><strong>{me.name}</strong><span>你{g.dealer===seat&&g.phase!=='waiting'?' · 庄家':''}</span></div><span>{g.phase==='playing'?g.options.canPass?'请选择响应动作':myTurn?'轮到你出牌':'等待其他玩家':me.ready?'已准备':'准备好就开局'}</span></div>
 <div className="mj-actions">{['waiting','finished'].includes(g.phase)?<><Button className="mj-start" disabled={busy} onClick={()=>act('ready')}>{me.ready?<><Check size={18}/>已准备，取消</>:<><Check size={18}/>准备好了</>}</Button><span>{g.seats.filter(s=>s.ready).length} / 4 人已准备</span></>:g.phase==='playing'?g.options.canPass?<><span className="mj-response-tile"><MahjongTile tile={g.pending!.tile} small/></span>{g.options.claims.map(o=><Button key={o.key} className={o.kind==='hu'?'mj-hu':''} variant={o.kind==='hu'?'default':'outline'} disabled={busy} onClick={()=>act('claim',{key:o.key})}>{({chi:'吃',pong:'碰',kong:'杠',hu:'胡'} as Record<string,string>)[o.kind]}{o.kind==='chi'&&<small>{o.tiles.map(tileLabel).join('·')}</small>}</Button>)}<Button variant="ghost" disabled={busy} onClick={()=>act('pass')}>跳过</Button></>:myTurn?<>{g.options.canHu&&<Button className="mj-hu" disabled={busy} onClick={()=>act('hu')}>自摸 · 胡</Button>}{g.options.kongs.map(o=><Button variant="outline" key={o.key} disabled={busy} onClick={()=>act('kong',{key:o.key})}>{o.kind==='concealed'?'暗杠':'补杠'} {tileLabel(o.tiles[0])}</Button>)}<span className="mj-selection-hint">{selected===null?'选择一张手牌':`已选择 ${tileLabel(selected)}`}</span><Button disabled={busy||selected===null} onClick={()=>act('discard',{tile:selected})}>出牌<ArrowRight size={17}/></Button></>:<p>{status}</p>:null}</div>
 {ownTiles.length>0&&<div className="mj-hand" aria-label="你的手牌">{ownTiles.map(t=><MahjongTile tile={t} key={t} selected={selected===t} drawn={g.drawn===t} onClick={g.phase==='playing'?()=>setSelected(selected===t?null:t):undefined}/>)}</div>}
 {me.melds.length>0&&<div className="mj-own-melds">{me.melds.map((m,i)=><div key={i}><span>{m.concealed?'暗杠':m.kind==='chi'?'吃':m.kind==='pong'?'碰':'杠'}</span>{m.tiles.map(t=><MahjongTile tile={t} key={t} small/>)}</div>)}</div>}
 </div></section><aside className="mj-table-aside"><section className="mj-side-card"><div className="section-tag">这 一 桌</div><h3>136 张 · 基础试玩</h3><p>万筒条 + 东南西北中发白<br/>不换三张 · 不定缺</p><div className="mj-rule-facts"><span>胡牌结构<b>四组牌 + 一对将</b></span><span>自摸<b>每家付 1 分</b></span><span>点炮 / 抢杠<b>出牌者付 1 分</b></span><span>操作时限<b>{g.seconds} 秒</b></span></div><Rules/></section><section className="mj-side-card mj-log"><h3><History size={16}/>牌桌动态</h3>{g.log.length?<div>{g.log.slice(-15).reverse().map((l,i)=><p key={i}>{l.text}</p>)}</div>:<p>牌局开始后，公开动作会记录在这里。</p>}</section>{g.phase==='finished'&&<Dialog><DialogTrigger asChild><Button variant="outline">查看所有手牌</Button></DialogTrigger><DialogContent className="rules-modal"><DialogHeader><DialogTitle>本局手牌</DialogTitle><DialogDescription>结束后公开每位玩家的手牌与吃碰杠。</DialogDescription></DialogHeader><div className="mj-final-hands">{g.seats.map(s=><section key={s.id}><h3>{s.name}</h3><div>{s.hand.map(t=><MahjongTile tile={t} small key={t}/>)}</div>{s.melds.map((m,i)=><div key={i}><span>{m.concealed?'暗杠':m.kind==='chi'?'吃':m.kind==='pong'?'碰':'杠'}</span>{m.tiles.map(t=><MahjongTile tile={t} small key={t}/>)}</div>)}</section>)}</div></DialogContent></Dialog>}</aside></div>
 <div className="room-footnote"><span><ShieldCheck size={15}/>仅娱乐积分 · 对局中隐藏他人手牌</span><Button variant="ghost" size="sm" onClick={()=>setLeaveOpen(true)} disabled={g.phase==='playing'}><DoorOpen size={16}/>离开房间</Button></div></main>}
 <AlertDialog open={leaveOpen} onOpenChange={setLeaveOpen}><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>要先离座吗？</AlertDialogTitle><AlertDialogDescription>空出的座位可以留给其他朋友。之后仍可用房间号加入。</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel>继续坐着</AlertDialogCancel><AlertDialogAction disabled={busy} onClick={()=>act('leave')}>离开房间</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>
 </div>;
}
