"use client";
import {useCallback,useEffect,useRef,useState} from 'react';
import {ArrowLeft,ArrowRight,Check,ChevronRight,Club,Copy,DoorOpen,History,Info,Layers3,LogOut,Plus,Settings,ShieldCheck,Timer,Trophy,Users,X} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Select,SelectContent,SelectItem,SelectTrigger,SelectValue} from '@/components/ui/select';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogTrigger,DialogDescription} from '@/components/ui/dialog';
import {AlertDialog,AlertDialogContent,AlertDialogHeader,AlertDialogTitle,AlertDialogDescription,AlertDialogFooter,AlertDialogCancel,AlertDialogAction} from '@/components/ui/alert-dialog';
import {RoomChat} from '@/components/room-chat';
import {MahjongRoundHands} from '@/components/round-hands';
import {soloPractice} from '@/lib/practice/types';
import {TableSound} from '@/components/table-sound';
import AuthScreen from '@/components/auth-screen';
import {Bot} from 'lucide-react';
import {RoomMode,PracticeBanner} from '@/components/room-mode';
import {MahjongSurface,ExpandMahjong} from '@/components/mahjong-board';
import {MahjongTile} from '@/components/mahjong-tile';
import {MahjongRules} from '@/components/mahjong-rules';
import {WinPicker} from '@/components/mahjong-win-picker';
import {ReportDialog,RoundDetails} from '@/components/mahjong-report';
import {api} from '@/lib/client';
import {tileLabel} from '@/lib/mahjong/engine';
import type {MahjongView} from '@/lib/mahjong/game';
import {HAM,MODERN_PRESETS,isHamRules} from '@/lib/mahjong/rules';
import {typeName} from '@/lib/mahjong/solver';
import {chips,publicRound} from '@/lib/mahjong/report';

type User={id:string;name:string;username:string;role:string;score:number};
type Room={code:string;title:string;revision:number;serverNow:number;receivedAt:number;game:MahjongView};
type RecordItem={id:string;room_code:string;created:number;result:{practice?:boolean;schemaVersion?:number;winner:number;winType:string;seats:{id:string;name:string;delta:number|string}[]}};
type Lobby={user:User;config:{announcement:string;seconds:number;maintenance:boolean};activeRoom:string|null;activeKind:string|null;records:RecordItem[];tables:{code:string;title:string;updated:number}[]};
function Avatar({name,index=0}:{name:string;index?:number}){return <span className={`avatar avatar-${index%3}`}>{name.slice(0,1).toUpperCase()}</span>}
export default function MahjongPage(){
 const [user,setUser]=useState<User|null>(null),[loaded,setLoaded]=useState(false),[lobby,setLobby]=useState<Lobby|null>(null),[room,setRoom]=useState<Room|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[code,setCode]=useState(''),[title,setTitle]=useState('');
 const [createOpen,setCreateOpen]=useState(false),[endAction,setEndAction]=useState<'leave'|'end_table'|'end_practice'|null>(null),[selected,setSelected]=useState<number|null>(null),[clock,setClock]=useState(Date.now()),[copied,setCopied]=useState(false);
 const [mode,setMode]=useState('friends');
 const [rulesId,setRulesId]=useState(HAM.id),[initial,setInitial]=useState('1000'),[base,setBase]=useState('10');
 const roomRef=useRef<Room|null>(null);roomRef.current=room;
 const accept=useCallback((next:Room)=>setRoom(prev=>!prev||prev.code!==next.code||next.revision>=prev.revision?{...next,receivedAt:Date.now()}:prev),[]);
 const fail=useCallback((e:Error&{status?:number})=>{setError(e.message);if(e.status===401){setUser(null);setRoom(null)}},[]);
 const loadLobby=useCallback(async()=>{const d=await api('/api/mahjong');setLobby(d);setUser(d.user);return d;},[]);
 useEffect(()=>{const requested=new URLSearchParams(location.search).get('room');if(requested&&/^\d{6}$/.test(requested))setCode(requested);api('/api/auth').then(d=>setUser(d.user)).catch(e=>setError(e.message)).finally(()=>setLoaded(true));},[]);
 useEffect(()=>{if(user?.id)loadLobby().catch(fail)},[user?.id,loadLobby,fail]);
 useEffect(()=>{if(!room?.code)return;let active=true,pending=false;const current=room.code;const poll=async()=>{if(pending)return;pending=true;try{const d=await api('/api/mahjong?room='+current);if(active&&roomRef.current?.code===current)accept(d)}catch(e){if(active)fail(e as Error)}finally{pending=false}};const id=setInterval(poll,1500);return()=>{active=false;clearInterval(id)};},[room?.code,accept,fail]);
 useEffect(()=>{const id=setInterval(()=>setClock(Date.now()),300);return()=>clearInterval(id)},[]);
 useEffect(()=>{window.scrollTo({top:0,behavior:'auto'});},[room?.code]);
 const g=room?.game,seat=g?.seats.findIndex(s=>s.id===user?.id)??-1,me=g?.seats[seat];
 useEffect(()=>setSelected(null),[me?.hand.join(',')]);
 useEffect(()=>{if(g?.phase==='finished'||g?.phase==='closed')loadLobby().catch(fail)},[g?.phase,loadLobby,fail]);
 async function act(action:string,extra:Record<string,unknown>={}){if(busy)return;setBusy(true);setError('');try{const r=roomRef.current,d=await api('/api/mahjong',{action,code:r?.code||code,revision:r?.revision,...extra});if(d.redirect){location.assign(d.redirect);return;}if(d.left){setRoom(null);await loadLobby()}else accept(d);setCreateOpen(false);setEndAction(null);}catch(e){fail(e as Error);if((e as {status?:number}).status===409&&roomRef.current)api('/api/mahjong?room='+roomRef.current.code).then(accept).catch(fail)}finally{setBusy(false)}}
 async function resume(){if(lobby?.activeKind==='landlord'){location.assign('/?room='+lobby.activeRoom);return;}setBusy(true);try{accept(await api('/api/mahjong?room='+lobby?.activeRoom))}catch(e){fail(e as Error)}finally{setBusy(false)}}
 async function copy(){try{await navigator.clipboard.writeText(`${location.origin}/mahjong?room=${room!.code}`);setCopied(true);setTimeout(()=>setCopied(false),2000)}catch{setError('请把房间号 '+room!.code+' 发给朋友')}}
 if(!loaded)return <main className="mj-loading"><span className="brand-icon"><Club size={22}/></span><p>正在打开游戏室…</p></main>;
 if(!user)return <><AuthScreen onAuth={setUser}/>{error&&<div className="floating-error" role="alert">{error}<button onClick={()=>location.reload()}>重试</button></div>}</>;
 const offset=room?room.serverNow-room.receivedAt:0,seconds=g?Math.max(0,Math.ceil((g.deadline-clock-offset)/1000)):0;
 const myTurn=g?.phase==='playing'&&!g.pending&&g.turn===seat;
 const ownTiles=me?[...me.hand.filter(t=>t!==g?.drawn),...(g?.drawn!==null&&g?.drawn!==undefined&&me.hand.includes(g.drawn)?[g.drawn]:[])]:[];
 const solo=soloPractice(g||{}),botControls=g?.phase==='waiting'&&g.host===user.id&&!solo&&g.session&&!g.session.fixed?{busy,add:()=>{void act('add_bot')},remove:(botId:string)=>{void act('remove_bot',{botId})}}:undefined;
 const status=g?.phase==='waiting'?solo?'陪练已就位':g.seats.length===4?'四人已到齐，准备开局':'等朋友入座':g?.phase==='closed'?'这桌已结束':g?.phase==='finished'?g.winType==='draw'?'本局流局':g.winType==='aborted'?'本局中止':`${g.seats[g.winner]?.name} ${g.winType==='self'?'自摸':g.winType==='rob'?'抢杠胡':'胡牌'}`:g?.phase==='choosing'?`${g.seats[g.winner]?.name} 正在选择胡牌方案`:g?.pending?(g.options.canPass?'轮到你响应这张牌':'等待吃碰杠胡选择'):myTurn?'轮到你出牌':`等待 ${g?.seats[g.turn]?.name} 出牌`;
 const gameRules=g?.rules??HAM,ham=isHamRules(gameRules.id);

 return <div className="app-shell mj-shell"><header className="app-header"><a href="/" className="brand"><span className="brand-icon"><Club size={21}/></span><span>娱乐中心<small>好 友 游 戏 室</small></span></a><nav className="game-nav" aria-label="选择游戏"><a href="/">斗地主</a><a href="/mahjong" aria-current="page">麻将</a></nav><div className="header-right"><TableSound room={room} userId={user.id} seconds={seconds}/><MahjongRules rulesId={gameRules.id} name={gameRules.name}/>{user.role==='admin'&&<Button variant="ghost" size="icon" asChild><a href="/admin" aria-label="管理后台"><Settings size={18}/></a></Button>}<span className="header-user"><Avatar name={user.name}/><span>{user.name}</span></span><Button variant="ghost" size="icon" aria-label="退出登录" onClick={()=>api('/api/auth',{action:'logout'}).then(()=>{setUser(null);setRoom(null);setLobby(null)})}><LogOut size={18}/></Button></div></header>
 {error&&<div className="connection-error" role="alert">{error}<button aria-label="关闭提示" onClick={()=>setError('')}><X size={17}/></button></div>}
 {!room||!g||!me?<main className="mj-lobby"><section className="mj-lobby-main"><div className="lobby-heading"><div className="section-tag">再 聚 一 桌</div><h1>四个人，刚刚好。</h1><p>开一桌，按自己的规矩玩。</p></div>{lobby?.config.announcement&&<div className="announcement"><Info size={17}/><span>{lobby.config.announcement}</span></div>}
 <section className="mj-welcome"><div className="mj-welcome-top"><span className="mj-badge">ham 规 · 已就位</span><span>02 / MAHJONG</span></div><div className="mj-welcome-body"><div><h2>麻将</h2><p>赖子怎么用，这一手你说了算。</p><div className="mj-summary"><span><Users size={16}/>四人好友房</span><span>136 张 · 无花牌</span></div>{lobby?.activeRoom?<Button className="mj-start" onClick={resume} disabled={busy}>{lobby.activeKind==='mahjong'?'回到麻将桌':'回到斗地主房间'}<ArrowRight size={18}/></Button>:<Dialog open={createOpen} onOpenChange={setCreateOpen}><div className="create-actions"><DialogTrigger asChild><Button className="mj-start" disabled={!lobby||lobby.config.maintenance} onClick={()=>setMode('friends')}><Plus size={19}/>开一桌麻将</Button></DialogTrigger><Button className="practice-start" variant="outline" disabled={!lobby||lobby.config.maintenance} onClick={()=>{setMode('practice');setCreateOpen(true)}}><Bot size={18}/>人机测试</Button></div><DialogContent className="ham-create-modal"><DialogHeader><DialogTitle>开一桌麻将</DialogTitle><DialogDescription>{mode==='practice'?'三位进阶陪练自动入座，支持 ham 规和基础试玩。':'四人准备后发牌。这桌的规则和筹码从建房时确定。'}</DialogDescription></DialogHeader><form className="stack-form" onSubmit={e=>{e.preventDefault();act('create',{title,mode,rulesId,initialChips:initial,baseChips:base})}}><RoomMode mode={mode} onChange={setMode} bots={3}/><label htmlFor="mj-title">房间名称</label><Input id="mj-title" maxLength={24} value={title} onChange={e=>setTitle(e.target.value)} placeholder={`${user.name} 的麻将桌`}/><label htmlFor="mj-rule">麻将规则</label><Select value={rulesId} onValueChange={setRulesId}><SelectTrigger id="mj-rule"><SelectValue/></SelectTrigger><SelectContent>{MODERN_PRESETS.map(r=><SelectItem value={r.id} key={r.id}>{r.name}</SelectItem>)}</SelectContent></Select><div className="ham-create-chips"><label htmlFor="mj-initial">每人初始筹码<Input id="mj-initial" inputMode="numeric" pattern="[1-9][0-9]*" maxLength={30} value={initial} onChange={e=>setInitial(e.target.value.replace(/\D/g,''))} required/></label><label htmlFor="mj-base">基础筹码 / 局<Input id="mj-base" inputMode="numeric" pattern="[1-9][0-9]*" maxLength={30} value={base} onChange={e=>setBase(e.target.value.replace(/\D/g,''))} required/></label></div><div className="mj-room-rules"><b>{rulesId===HAM.id?'ham 规 · 随机赖子 · 白板替代':'基础试玩 · 四组牌加一对将'}</b><p>{rulesId===HAM.id?'自摸 2 倍，点炮 1 倍，无赖子不加倍。胡牌自主选赖子方案，先翻奖牌加分再乘倍数。明杠 1 单位、暗杠 2 单位，保留末 12 张。':'不换三张、不定缺，可吃碰杠。没有赖子、特殊倍数和奖牌，牌墙摸完流局。'}<br/>出牌 {lobby?.config.seconds||30} 秒 · 响应 8 秒{rulesId===HAM.id?' · 选方案 60 秒':''}</p></div><Button type="submit" disabled={busy}>{busy?'正在开桌…':'创建房间'}<ArrowRight size={17}/></Button></form></DialogContent></Dialog>}</div><div className="mj-intro-tiles" aria-label="万筒条与赖子"><MahjongTile tile={16}/><MahjongTile tile={52} wildcard={13}/><MahjongTile tile={88}/><MahjongTile tile={132} wildcard={13}/></div></div><div className="mj-welcome-footer"><span>吃 · 碰 · 杠 · 胡</span><span>独立筹码 · 完整战报</span></div></section>
 <section className="join-box"><div><h3>朋友已经开桌了？</h3><p>输入房间号，留个位置给自己。</p></div><form onSubmit={e=>{e.preventDefault();act('join')}}><Input aria-label="6 位麻将房间号" placeholder="6 位房间号" inputMode="numeric" pattern="[0-9]{6}" maxLength={6} value={code} onChange={e=>setCode(e.target.value.replace(/\D/g,''))} required/><Button type="submit" disabled={busy||code.length!==6}>入座<ChevronRight size={17}/></Button></form></section>
 <div className="mj-rule-strip"><div><Layers3 size={20}/><b>赖子，自主决定</b><span>完整方案与倍数一目了然</span></div><div><Timer size={20}/><b>有响应，才等待</b><span>掉线后可回到原桌</span></div><div><Trophy size={20}/><b>好牌值得留念</b><span>结算战报一键保存</span></div></div>
 </section><aside className="mj-lobby-aside"><div className="profile-card"><Avatar name={user.name}/><h3>{user.name}</h3><span>每桌筹码独立结算</span><div className="profile-score"><span>历史账号积分</span><strong>{chips(user.score,true)}</strong></div></div><section className="recent"><h3><History size={17}/>最近麻将对局</h3>{!lobby?<p className="muted">正在读取…</p>:!lobby.records.length?<div className="empty-history"><Layers3 size={30}/><p>第一桌，等你开场。</p><span>每局收支和胡牌方案都会留在这里。</span></div>:lobby.records.map(r=>{const p=r.result.seats.find(s=>s.id===user.id)!;const content=<div className="history-row ham-history-row"><div><b>{r.result.winType==='draw'?'流局':r.result.winType==='aborted'?'本局中止':r.result.seats[r.result.winner]?.id===user.id?'胡了一手好牌':'本局已结算'}</b><span>{r.result.practice?'人机对局 · ':''}{new Date(r.created).toLocaleDateString('zh-CN')} · {r.result.schemaVersion===2?'查看战报':'旧版积分'}</span></div><strong className={BigInt(p.delta)>=0n?'positive':'negative'}>{chips(p.delta,true)}</strong></div>;return r.result.schemaVersion===2?<ReportDialog key={r.id} code={r.room_code} round={r.id}><button className="ham-history-button">{content}</button></ReportDialog>:<div key={r.id}>{content}</div>})}</section>{!!lobby?.tables.length&&<section className="recent"><h3><Trophy size={17}/>已结束的牌桌</h3>{lobby.tables.map(t=><ReportDialog key={t.code} code={t.code}><button className="ham-table-history"><b>{t.title}</b><span>整桌战报<ChevronRight size={15}/></span></button></ReportDialog>)}</section>}<p className="aside-note"><ShieldCheck size={15}/>独立账号 · 分享由你主动生成</p></aside></main>:
 <main className="mj-room"><div className="room-toolbar"><div><Button variant="ghost" size="icon" aria-label="返回麻将大厅" onClick={()=>{setRoom(null);loadLobby().catch(fail)}}><ArrowLeft size={20}/></Button><div><h2>{room.title}</h2><span>房间 {room.code} · {g.rules.name}{g.session?' · 基础 '+chips(g.session.baseChips)+' 筹码':''}</span></div></div>{g.phase!=='closed'&&(solo?<Button variant="outline" onClick={()=>setEndAction('end_practice')}><DoorOpen size={16}/>结束测试</Button>:<Button variant="outline" onClick={copy}>{copied?<Check size={16}/>:<Copy size={16}/>}<span>{copied?'已复制':'邀请朋友'}</span></Button>)}</div>{g.practice&&<PracticeBanner mahjong mixed={!solo}/>}
 <div className="mj-table-layout"><section className="mj-board" aria-label="四人麻将牌桌"><MahjongSurface g={g} seat={seat} seconds={seconds} botControls={botControls}>
 {g.phase==='waiting'?<div className="mj-waiting"><div className="mj-wait-icon"><Layers3 size={29}/></div><span className="section-tag">四 人 一 桌</span><h2>{status}</h2><p>{solo?'三位机器人已准备好':g.seats.length<4?'邀请朋友，或添加人机':'同桌玩家已到齐'}<br/>{g.practice?'每位真人准备后发牌':'四人准备后自动发牌'}</p><div className="mj-room-code">{room.code}</div>{g.session&&<p>每人 {chips(g.session.initialChips)} 筹码<br/>基础 {chips(g.session.baseChips)} 筹码 / 局</p>}</div>:g.phase==='closed'?<div className="mj-waiting"><Trophy size={33}/><h2>这桌已结束</h2><p>{g.session?'所有已完成的收支都保存在整桌战报中。':'未完成的本局不计分。'}</p>{g.session&&<ReportDialog code={room.code}/>}<Button variant="ghost" onClick={()=>{setRoom(null);loadLobby().catch(fail)}}>返回大厅</Button></div>:g.phase==='finished'?<div className="mj-results"><div className="section-tag">本 局 结 算</div><h2>{status}</h2><p>{g.session?g.winType==='draw'?'已成功的杠分保留':`完整计算与奖牌结果见本局战报`:g.winType==='draw'?'牌墙已摸完，本局不计分':g.winType==='self'?'自摸，每位牌友支付 1 分':'出牌者支付 1 分'}</p><div className="mj-score-grid">{g.seats.map((s,i)=><div key={s.id}><span>{s.name}</span><strong className={BigInt(g.deltas[i])>=0n?'positive':'negative'}>{chips(g.deltas[i],true)}</strong></div>)}</div>{g.result&&<ReportDialog code={room.code} round={g.round}/>}<p>准备好，再来一局。</p></div>:g.phase==='choosing'?<div className="ham-choosing-stage"><span className="section-tag">先 选 牌 · 后 翻 奖</span><h2>{g.seats[g.winner].name} 胡牌</h2><p>{g.canChoose?'请选定赖子的完整用法，确认后再抽奖。':'等待胡牌者确认方案，奖牌尚未揭开。'}</p><div className="ham-sealed-awards"><MahjongTile hidden/><MahjongTile hidden/></div><div className="ham-choice-time"><Timer size={18}/>{seconds} 秒</div>{g.canChoose&&<WinPicker key={g.round} code={room.code} round={g.round} seconds={seconds} busy={busy} onConfirm={id=>act('confirm_win',{candidateId:id})}/>}</div>:null}
 </MahjongSurface>
 <div className={`mj-self ${myTurn?'is-my-turn':''}`}><div className="mj-self-top"><div><Avatar name={me.name}/><strong>{me.name}</strong><span>你{g.dealer===seat&&g.roundNumber>0?' · 庄家':''}</span></div><span className="ham-own-balance">{me.balance!==null?chips(me.balance)+' 筹码':me.ready?'已准备':'准备好就开局'}</span></div>
 <div className="mj-actions">{['waiting','finished'].includes(g.phase)?<><Button className="mj-start" disabled={busy} onClick={()=>act('ready')}>{me.ready?<><Check size={18}/>已准备，取消</>:<><Check size={18}/>准备好了</>}</Button><span>{g.seats.filter(s=>s.ready).length} / 4 人已准备</span></>:g.phase==='playing'?g.options.canPass?<><span className="mj-response-tile"><MahjongTile tile={g.pending!.tile} small wildcard={g.wildcard}/></span>{g.options.claims.map(o=><Button key={o.key} className={o.kind==='hu'?'mj-hu':''} variant={o.kind==='hu'?'default':'outline'} disabled={busy} onClick={()=>act('claim',{key:o.key})}>{({chi:'吃',pong:'碰',kong:'杠',hu:'胡'} as Record<string,string>)[o.kind]}{o.kind==='chi'&&<small>{o.tiles.map(tileLabel).join('·')}</small>}</Button>)}<Button variant="ghost" disabled={busy} onClick={()=>act('pass')}>跳过</Button></>:myTurn?<>{g.options.canHu&&<Button className="mj-hu" disabled={busy} onClick={()=>act('hu')}>自摸 · 胡</Button>}{g.options.kongs.map(o=><Button variant="outline" key={o.key} disabled={busy} onClick={()=>act('kong',{key:o.key})}>{o.kind==='concealed'?'暗杠':'补杠'} {tileLabel(o.tiles[0])}</Button>)}<span className="mj-selection-hint">{selected===null?'选择一张手牌':`已选择 ${tileLabel(selected)}`}</span><Button disabled={busy||selected===null} onClick={()=>act('discard',{tile:selected})}>出牌<ArrowRight size={17}/></Button></>:<p>{status}</p>:<p>{status}</p>}</div>
 {ownTiles.length>0&&g.phase!=='finished'&&<div className="mj-hand" aria-label="你的手牌">{ownTiles.map(t=><MahjongTile tile={t} key={t} selected={selected===t} drawn={g.drawn===t} wildcard={g.wildcard} onClick={g.phase==='playing'?()=>setSelected(selected===t?null:t):undefined}/>)}</div>}
 </div>{g.phase==='finished'&&<MahjongRoundHands g={g}/>}</section></div><div className="mj-table-tools"><ExpandMahjong g={g} seat={seat} seconds={seconds}/><Dialog><DialogTrigger asChild><Button variant="outline"><History size={16}/>牌桌详情</Button></DialogTrigger><DialogContent className="mj-details-modal"><DialogHeader><DialogTitle>牌桌详情</DialogTitle><DialogDescription>本桌规则、筹码收支与公开操作记录。</DialogDescription></DialogHeader><div className="mj-details-content"><section className="mj-side-card"><div className="section-tag">这 一 桌</div><h3>{g.rules.name}</h3><p>136 张 · 无花牌<br/>不换三张 · 不定缺</p><div className="mj-rule-facts">{g.session?<><span>初始筹码<b>{chips(g.session.initialChips)} / 人</b></span><span>基础筹码<b>{chips(g.session.baseChips)} / 局</b></span><span>胡牌付款<b>自摸三家 · 点炮一家</b></span><span>响应时间<b>8 秒</b></span>{ham&&<><span>流局保留<b>12 张</b></span><span>庄家规则<b>庄赢或流局连庄</b></span>{g.wildcard>=0&&<span>赖子 / 白板代牌<b>{typeName(g.wildcard)}</b></span>}</>}</>:<span>胡牌基础分<b>1 分</b></span>}<span>出牌时限<b>{g.seconds} 秒</b></span></div><MahjongRules rulesId={g.rules.id} name={g.rules.name}/></section>
 {g.entries.length>0&&<section className="mj-side-card ham-live-ledger"><h3>本局筹码流水</h3>{g.entries.map(e=><p key={e.id}>{e.description}</p>)}</section>}
 {g.result&&<section className="mj-side-card ham-current-result"><h3>本局计算</h3><RoundDetails round={publicRound(g.result)}/></section>}
 <section className="mj-side-card mj-log"><h3><History size={16}/>牌桌动态</h3>{g.log.length?<div>{g.log.slice(-15).reverse().map((l,i)=><p key={i}>{l.text}</p>)}</div>:<p>牌局开始后，公开动作会记录在这里。</p>}</section>

 </div></DialogContent></Dialog></div><div className="ham-room-footer"><span>{solo?'人机测试可随时结束，已完成的战报会保留。':g.session?.fixed?'本桌已固定四位牌友，掉线可重连。':'首局开始前可以自由入座、离座。'}</span>{solo&&g.phase!=='closed'?<Button variant="ghost" onClick={()=>setEndAction('end_practice')}><DoorOpen size={16}/>结束测试</Button>:g.session&&g.host===user.id&&['waiting','finished'].includes(g.phase)?<Button variant="ghost" onClick={()=>setEndAction('end_table')}><DoorOpen size={16}/>结束整桌</Button>:(!g.session||!g.session.fixed)&&g.phase!=='closed'?<Button variant="ghost" onClick={()=>setEndAction('leave')}><DoorOpen size={16}/>离开房间</Button>:null}</div></main>}
 {room&&<RoomChat key={room.code} code={room.code} closed={g?.phase==='closed'}/>}
 <AlertDialog open={!!endAction} onOpenChange={v=>!v&&setEndAction(null)}><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>{endAction==='end_practice'?'结束人机测试？':endAction==='end_table'?'结束这一桌？':'离开房间？'}</AlertDialogTitle><AlertDialogDescription>{endAction==='end_practice'?'未完成的本局记为中止，并撤销本局杠分。已完成的筹码收支和战报保留。':endAction==='end_table'?'结余筹码与每局收支将保存为整桌战报。结束后，四位玩家可以各自开新桌。':'离座后需要重新加入房间。对局进行中只能暂时返回大厅，座位会保留。'}</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel>取消</AlertDialogCancel><AlertDialogAction disabled={busy} onClick={()=>endAction&&act(endAction)}>{endAction==='end_practice'?'结束测试':endAction==='end_table'?'结束并生成战报':'确认离开'}</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>
 </div>;
}
